/**
 * ExpiryForecastRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExpiryForecastRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExpiryForecastRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExpiryForecastRepository,
} from "@vouchstone/services/evidence";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExpiryForecastRepositoryDdb } from "./expiry-forecast-repository.ddb.js";

/**
 * ExpiryForecastRepositoryAdapter
 *
 * Implements ExpiryForecastRepository port for infrastructure layer.
 */
export class ExpiryForecastRepositoryAdapter implements ExpiryForecastRepository {
  private readonly ddb: ExpiryForecastRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExpiryForecastRepositoryDdb(this.dynamoClient);
  }

  async getEvidenceExpiryForecast(input: Parameters<ExpiryForecastRepository['getEvidenceExpiryForecast']>[0]): Promise<Awaited<ReturnType<ExpiryForecastRepository['getEvidenceExpiryForecast']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getEvidenceExpiryForecast(input);
  }
}
