/**
 * Handlers for Outcome
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ExercisesDomainModule } from "../dependencies/exercises-ddd.dependencies.js";
import type { RecordExerciseOutcomeInput } from "@vouchstone/services/exercises";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/exercises/{exerciseId}/outcome
 * Operation: recordExerciseOutcome
 */
export async function recordExerciseOutcome(
  request: FastifyRequest<{ Params: { exerciseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ExercisesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordExerciseOutcomeInput = {
    exerciseId: request.params.exerciseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.outcomes.get.execute(input);
  return reply.code(201).send(result);
}


