/**
 * Finding DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Finding DTOs
 *
 * DDD: Application DTOs for Finding use cases.
 */

import type { ListFindingsParams, RaiseFindingRequestInput } from "@vouchstone/core/findings/types";

export type ListFindingsInput = ListFindingsParams;

export type RaiseFindingInput = RaiseFindingRequestInput;

export type ListFindingsOutput = {};

export type RaiseFindingOutput = {};
