/**
 * Remediation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Remediation DTOs
 *
 * DDD: Application DTOs for Remediation use cases.
 */

import type { UpdateRemediationCommitmentParams, UpdateRemediationCommitmentRequestInput } from "@vouchstone/core/findings/types";

export type UpdateRemediationCommitmentInput = UpdateRemediationCommitmentParams & UpdateRemediationCommitmentRequestInput;

export type UpdateRemediationCommitmentOutput = {};
