/**
 * AttributeIncidentDiscovery handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { attributeIncidentDiscovery } from "@vouchstone/api-server/domains/attribution/handlers";
import type { AttributionDDDDependencies } from "@vouchstone/api-server/domains/attribution";
import { createAttribution as createAttributionEntity } from "@vouchstone/factories/attribution";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vouchstone/tests/shared";
import { ATTRIBUTION_USE_CASES } from "../__factories__/use-cases.js";

describe("AttributeIncidentDiscovery", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AttributionDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AttributionDDDDependencies>(
      ATTRIBUTION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createAttributionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAttributeIncidentDiscovery, "execute").mockResolvedValue(useCaseResult);

    await attributeIncidentDiscovery(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAttributeIncidentDiscovery.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
