/**
 * ExportRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExportRepositoryDdb
 *
 * DDD: Infrastructure adapter implementing Export repository using DynamoDB.
 * Generated from x-dynamodb metadata in OpenAPI schema.
 */

import type { ExportRepository } from "@vouchstone/services/assurance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { getCoreTableName, getBaseTableName, getAnalyticsTableName } from "../_shared/dynamodb-utils.js";
import { sanitizeItem } from "../_shared/dynamodb-key-helpers.js";
import { ulid } from "ulid";

/**
 * ExportRepositoryDdb using DynamoDB table (type: core)
 *
 * Entity Type: EXPORT
 * Entity Token: EXPORT
 * SK Prefix: EXPORT
 */
export class ExportRepositoryDdb implements ExportRepository {
  private readonly TABLE_NAME: string;
  // Metadata from x-dynamodb annotation - all values are dynamic
  private readonly ENTITY_TYPE = "EXPORT";
  private readonly ENTITY_TOKEN = "EXPORT";
  private readonly SK_PREFIX = "EXPORT";
  private readonly IS_CHILD_ENTITY = false;
  private readonly CREATED_AT_FIELD = "generatedAt";
  private readonly UPDATED_AT_FIELD = "updatedAt";
  private readonly SOFT_DELETE_ENABLED = false;
  private readonly DOMAIN = "ASSURANCE";
  private readonly ENTITY_TYPE_PK = "EXPORTS";
  private generateCorrelationId(): string {
    const domainPrefix = "asr";
    return `${domainPrefix}_${ulid().toLowerCase()}`;
  }
  /** Partition key from x-dynamodb: ORG#orgId#DOMAIN#COLLECTION#entityId (id in PK). */
  private buildPK(orgId: string, entityId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}#${entityId}`;
  }
  /** Collection prefix for list/query: ORG#orgId#DOMAIN#COLLECTION (no entityId). */
  private getCollectionPK(orgId: string): string {
    return `ORG#${orgId}#${this.DOMAIN}#${this.ENTITY_TYPE_PK}`;
  }
  /** Deterministic SK: ENTITY#entityId (legacy …#TIMESTAMP#ts dual-read via begins_with). */
  private buildSK(entityId: string, _identifier?: string): string {
    return `${this.ENTITY_TOKEN}#${entityId}`;
  }
  /** GSI time SK: updatedAt#entityId (uniqueness under bulk writes). */
  private buildGsiSK(updatedAt: string, entityId: string): string {
    return `${updatedAt}#${entityId}`;
  }
  /** GSI2 list-by-org: ORG#orgId#COLLECTION */
  private buildGSI2PK(orgId: string): string {
    return `ORG#${orgId}#${this.ENTITY_TYPE_PK}`;
  }


  constructor(private readonly dynamoClient: AdapterDynamoDBClient) {
    const tableTypeFromMetadata = "core";
    const tableTypeMap = {
      core: getCoreTableName,
      base: getBaseTableName,
      analytics: getAnalyticsTableName,
    };
    const tableNameFn = tableTypeMap[tableTypeFromMetadata] || getCoreTableName;
    this.TABLE_NAME = tableNameFn();
  }

  async exportAssurancePackage(input: Parameters<ExportRepository['exportAssurancePackage']>[0]): Promise<Awaited<ReturnType<ExportRepository['exportAssurancePackage']>>> {
    const inputExt = input as Record<string, unknown>;

    if (!input || !inputExt.orgId) {
      throw new Error("Missing required parameter: input or orgId");
    }
    const prefix = this.getCollectionPK(inputExt.orgId as string);
    const limit = inputExt?.limit
      ? (typeof inputExt.limit === "string" ? parseInt(inputExt.limit, 10) : Number(inputExt.limit))
      : 1000;
    const result = await this.dynamoClient.scan({
      TableName: this.TABLE_NAME,
      FilterExpression: "begins_with(PK, :prefix)",
      ExpressionAttributeValues: { ":prefix": prefix },
      Limit: limit,
    });
    const items = ((result.Items || []) as Record<string, unknown>[]).map((i) => sanitizeItem(i));
    const exportId = `asr_${ulid().toLowerCase()}`;
    return {
      data: {
        exportId,
        status: "completed" as const,
        downloadUrl: null,
        items,
      } as unknown as any,
      meta: {
        correlationId: (inputExt?.correlationId as string) || this.generateCorrelationId(),
        timestamp: new Date().toISOString(),
      } as unknown as any,
    };
  }
}
