/**
 * StatementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StatementRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements StatementRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  StatementRepository,
} from "@vouchstone/services/assurance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { StatementRepositoryDdb } from "./statement-repository.ddb.js";

/**
 * StatementRepositoryAdapter
 *
 * Implements StatementRepository port for infrastructure layer.
 */
export class StatementRepositoryAdapter implements StatementRepository {
  private readonly ddb: StatementRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new StatementRepositoryDdb(this.dynamoClient);
  }

  async listAssuranceStatements(input: Parameters<StatementRepository['listAssuranceStatements']>[0]): Promise<Awaited<ReturnType<StatementRepository['listAssuranceStatements']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAssuranceStatements(input);
  }

  async signAssuranceStatement(input: Parameters<StatementRepository['signAssuranceStatement']>[0]): Promise<Awaited<ReturnType<StatementRepository['signAssuranceStatement']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.signAssuranceStatement(input);
  }
}
