/**
 * ListAssuranceStatements handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAssuranceStatements } from "@vouchstone/api-server/domains/assurance/handlers";
import type { AssuranceDDDDependencies } from "@vouchstone/api-server/domains/assurance";
import { createStatement as createStatementEntity } from "@vouchstone/factories/assurance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vouchstone/tests/shared";
import { ASSURANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAssuranceStatements", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssuranceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssuranceDDDDependencies>(
      ASSURANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createStatementEntity({ orgId }),
      createStatementEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAssuranceStatements, "execute").mockResolvedValue(useCaseResult);

    await listAssuranceStatements(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAssuranceStatements.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
