/**
 * SignAssuranceStatement handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { signAssuranceStatement } from "@vouchstone/api-server/domains/assurance/handlers";
import type { AssuranceDDDDependencies } from "@vouchstone/api-server/domains/assurance";
import { createStatement as createStatementEntity } from "@vouchstone/factories/assurance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vouchstone/tests/shared";
import { ASSURANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("SignAssuranceStatement", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssuranceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssuranceDDDDependencies>(
      ASSURANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createStatementEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSignAssuranceStatement, "execute").mockResolvedValue(useCaseResult);

    await signAssuranceStatement(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSignAssuranceStatement.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
