/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Domains Domain Use Cases
 * 
 * List of all use case names for the domains domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const DOMAINS_USE_CASES = [
  "executeGetDomainScore",
  "executeListDomainScores",
  "executeProposeDomainClaim"
] as const;
