/**
 * Routes for Attribution
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { attributeIncidentDiscovery } from "../handlers/attribution.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function attributionRoutes(fastify: FastifyInstance) {
  // POST /v1/incidents/{incidentId}/attribution (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/incidents/:incidentId/attribution",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { incidentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAttributionDependenciesForRequest();
        await attributeIncidentDiscovery(request, reply, deps);
      });
    }
  );


}
