/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { detectionIntervalRoutes } from "./detection-interval.routes.js";
export { discoveryShareRoutes } from "./discovery-share.routes.js";
export { attributionRoutes } from "./attribution.routes.js";
