/**
 * Repository interface for Score
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ScoreEntity
} from "../models/score.entity.js";
import type {
  ListDomainScoresParams
} from "../types/index.js";
/**
 * ScoreRepository Interface
 */
export interface ScoreRepository extends ReadRepository<ScoreEntity, string, ListDomainScoresParams> {

}
