/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Findings */
        get: operations["listFindings"];
        put?: never;
        /** Raise Finding */
        post: operations["raiseFinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/findings/{findingId}/remediation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                findingId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update Remediation Commitment */
        put: operations["updateRemediationCommitment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DomainKey: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
        RemediationCommitment: {
            ownerId: string;
            /** Format: date */
            targetDate: string;
            plan?: string;
            revisionCount?: number;
            acceptedRiskRationale?: string;
            /** Format: date-time */
            closedAt?: string;
            closureApprovedBy?: string;
        };
        Finding: {
            id: string;
            title: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            /** @enum {string} */
            state: "open" | "overdue" | "closed" | "accepted_risk";
            domains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
            assetIds?: string[];
            ownerId: string;
            /** Format: date */
            dueDate: string;
            origin?: string;
            suppressingDomainScore?: boolean;
            remediation?: {
                ownerId: string;
                /** Format: date */
                targetDate: string;
                plan?: string;
                revisionCount?: number;
                acceptedRiskRationale?: string;
                /** Format: date-time */
                closedAt?: string;
                closureApprovedBy?: string;
            };
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ListEnvelopeFinding: {
            data: {
                items: {
                    id: string;
                    title: string;
                    /** @enum {string} */
                    severity: "low" | "medium" | "high" | "critical";
                    /** @enum {string} */
                    state: "open" | "overdue" | "closed" | "accepted_risk";
                    domains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                    assetIds?: string[];
                    ownerId: string;
                    /** Format: date */
                    dueDate: string;
                    origin?: string;
                    suppressingDomainScore?: boolean;
                    remediation?: {
                        ownerId: string;
                        /** Format: date */
                        targetDate: string;
                        plan?: string;
                        revisionCount?: number;
                        acceptedRiskRationale?: string;
                        /** Format: date-time */
                        closedAt?: string;
                        closureApprovedBy?: string;
                    };
                }[];
                nextCursor?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        FindingCreate: {
            title: string;
            description?: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
            assetIds?: string[];
            ownerId: string;
            /** Format: date */
            dueDate: string;
            /** @enum {string} */
            origin?: "exercise" | "incident" | "evidence_lapse" | "audit" | "allocation_divergence" | "coverage_gap";
        };
        DataEnvelopeFinding: {
            data: {
                id: string;
                title: string;
                /** @enum {string} */
                severity: "low" | "medium" | "high" | "critical";
                /** @enum {string} */
                state: "open" | "overdue" | "closed" | "accepted_risk";
                domains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                assetIds?: string[];
                ownerId: string;
                /** Format: date */
                dueDate: string;
                origin?: string;
                suppressingDomainScore?: boolean;
                remediation?: {
                    ownerId: string;
                    /** Format: date */
                    targetDate: string;
                    plan?: string;
                    revisionCount?: number;
                    acceptedRiskRationale?: string;
                    /** Format: date-time */
                    closedAt?: string;
                    closureApprovedBy?: string;
                };
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        FindingId: string;
        /** @description Opaque pagination cursor from a previous page. */
        Cursor: string;
        /** @description Page size (1–200). */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFindings: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous page. */
                cursor?: string;
                /** @description Page size (1–200). */
                limit?: number;
                state?: "open" | "overdue" | "closed" | "accepted_risk";
                domain?: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Findings page with suppressed domain scores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                title: string;
                                /** @enum {string} */
                                severity: "low" | "medium" | "high" | "critical";
                                /** @enum {string} */
                                state: "open" | "overdue" | "closed" | "accepted_risk";
                                domains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                                assetIds?: string[];
                                ownerId: string;
                                /** Format: date */
                                dueDate: string;
                                origin?: string;
                                suppressingDomainScore?: boolean;
                                remediation?: {
                                    ownerId: string;
                                    /** Format: date */
                                    targetDate: string;
                                    plan?: string;
                                    revisionCount?: number;
                                    acceptedRiskRationale?: string;
                                    /** Format: date-time */
                                    closedAt?: string;
                                    closureApprovedBy?: string;
                                };
                            }[];
                            nextCursor?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    raiseFinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    description?: string;
                    /** @enum {string} */
                    severity: "low" | "medium" | "high" | "critical";
                    domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                    assetIds?: string[];
                    ownerId: string;
                    /** Format: date */
                    dueDate: string;
                    /** @enum {string} */
                    origin?: "exercise" | "incident" | "evidence_lapse" | "audit" | "allocation_divergence" | "coverage_gap";
                };
            };
        };
        responses: {
            /** @description Finding raised with a named owner and due date */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            title: string;
                            /** @enum {string} */
                            severity: "low" | "medium" | "high" | "critical";
                            /** @enum {string} */
                            state: "open" | "overdue" | "closed" | "accepted_risk";
                            domains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                            assetIds?: string[];
                            ownerId: string;
                            /** Format: date */
                            dueDate: string;
                            origin?: string;
                            suppressingDomainScore?: boolean;
                            remediation?: {
                                ownerId: string;
                                /** Format: date */
                                targetDate: string;
                                plan?: string;
                                revisionCount?: number;
                                acceptedRiskRationale?: string;
                                /** Format: date-time */
                                closedAt?: string;
                                closureApprovedBy?: string;
                            };
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateRemediationCommitment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                findingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ownerId: string;
                    /** Format: date */
                    targetDate: string;
                    plan?: string;
                    revisionCount?: number;
                    acceptedRiskRationale?: string;
                    /** Format: date-time */
                    closedAt?: string;
                    closureApprovedBy?: string;
                };
            };
        };
        responses: {
            /** @description Remediation commitment updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            title: string;
                            /** @enum {string} */
                            severity: "low" | "medium" | "high" | "critical";
                            /** @enum {string} */
                            state: "open" | "overdue" | "closed" | "accepted_risk";
                            domains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                            assetIds?: string[];
                            ownerId: string;
                            /** Format: date */
                            dueDate: string;
                            origin?: string;
                            suppressingDomainScore?: boolean;
                            remediation?: {
                                ownerId: string;
                                /** Format: date */
                                targetDate: string;
                                plan?: string;
                                revisionCount?: number;
                                acceptedRiskRationale?: string;
                                /** Format: date-time */
                                closedAt?: string;
                                closureApprovedBy?: string;
                            };
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
