/**
 * Routes for Attestation
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { attestPriorityAsset } from "../handlers/attestation.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function attestationRoutes(fastify: FastifyInstance) {
  // POST /v1/assets/{assetId}/attestation (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/assets/:assetId/attestation",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { assetId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssetsDependenciesForRequest();
        await attestPriorityAsset(request, reply, deps);
      });
    }
  );


}
