/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/allocation/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compares where the organisation believes impact concentrates against where control effort and spe...
         * @description Compares where the organisation believes impact concentrates against where control effort and spend actually go, and raises a standing divergence finding.
         */
        get: operations["getAllocationReconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/allocation/impact-beliefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Captures the organisation's stated belief about which threat classes carry the greatest impact, f...
         * @description Captures the organisation's stated belief about which threat classes carry the greatest impact, for reconciliation against actual investment.
         */
        post: operations["recordImpactBelief"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImpactBelief: {
            /** @enum {string} */
            threatClass: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
            believedImpactRank: number;
            /** Format: float */
            believedShare?: number;
            /** @enum {string} */
            capturedFrom: "executive_survey" | "risk_register" | "committee_minute" | "workshop";
            /** Format: date-time */
            capturedAt?: string;
            /**
             * Format: float
             * @description Stated confidence that internal controls would detect this threat class
             */
            trustInInternalControls?: number;
        };
        /** @enum {string} */
        DomainKey: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
        Money: {
            /** Format: double */
            amount: number;
            /** @example EUR */
            currency: string;
        };
        ControlInvestment: {
            /** @enum {string} */
            domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
            /** @enum {string} */
            threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
            amount: {
                /** Format: double */
                amount: number;
                /** @example EUR */
                currency: string;
            };
            /** Format: float */
            effortFullTimeEquivalents?: number;
            period: string;
            sourceSystem?: string;
        };
        AllocationDivergence: {
            threatClass?: string;
            /** Format: float */
            believedImpactShare?: number;
            /** Format: float */
            actualInvestmentShare?: number;
            /** Format: float */
            divergencePoints?: number;
            findingId?: string;
        };
        AllocationReconciliation: {
            period?: string;
            beliefs?: {
                /** @enum {string} */
                threatClass: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                believedImpactRank: number;
                /** Format: float */
                believedShare?: number;
                /** @enum {string} */
                capturedFrom: "executive_survey" | "risk_register" | "committee_minute" | "workshop";
                /** Format: date-time */
                capturedAt?: string;
                /**
                 * Format: float
                 * @description Stated confidence that internal controls would detect this threat class
                 */
                trustInInternalControls?: number;
            }[];
            investments?: {
                /** @enum {string} */
                domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                /** @enum {string} */
                threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                amount: {
                    /** Format: double */
                    amount: number;
                    /** @example EUR */
                    currency: string;
                };
                /** Format: float */
                effortFullTimeEquivalents?: number;
                period: string;
                sourceSystem?: string;
            }[];
            divergences?: {
                threatClass?: string;
                /** Format: float */
                believedImpactShare?: number;
                /** Format: float */
                actualInvestmentShare?: number;
                /** Format: float */
                divergencePoints?: number;
                findingId?: string;
            }[];
            standingFindingRaised?: boolean;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        DataEnvelopeAllocationReconciliation: {
            data: {
                period?: string;
                beliefs?: {
                    /** @enum {string} */
                    threatClass: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                    believedImpactRank: number;
                    /** Format: float */
                    believedShare?: number;
                    /** @enum {string} */
                    capturedFrom: "executive_survey" | "risk_register" | "committee_minute" | "workshop";
                    /** Format: date-time */
                    capturedAt?: string;
                    /**
                     * Format: float
                     * @description Stated confidence that internal controls would detect this threat class
                     */
                    trustInInternalControls?: number;
                }[];
                investments?: {
                    /** @enum {string} */
                    domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                    /** @enum {string} */
                    threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                    amount: {
                        /** Format: double */
                        amount: number;
                        /** @example EUR */
                        currency: string;
                    };
                    /** Format: float */
                    effortFullTimeEquivalents?: number;
                    period: string;
                    sourceSystem?: string;
                }[];
                divergences?: {
                    threatClass?: string;
                    /** Format: float */
                    believedImpactShare?: number;
                    /** Format: float */
                    actualInvestmentShare?: number;
                    /** Format: float */
                    divergencePoints?: number;
                    findingId?: string;
                }[];
                standingFindingRaised?: boolean;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        DataEnvelopeImpactBelief: {
            data: {
                /** @enum {string} */
                threatClass: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                believedImpactRank: number;
                /** Format: float */
                believedShare?: number;
                /** @enum {string} */
                capturedFrom: "executive_survey" | "risk_register" | "committee_minute" | "workshop";
                /** Format: date-time */
                capturedAt?: string;
                /**
                 * Format: float
                 * @description Stated confidence that internal controls would detect this threat class
                 */
                trustInInternalControls?: number;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllocationReconciliation: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Allocation reconciliation with divergences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            period?: string;
                            beliefs?: {
                                /** @enum {string} */
                                threatClass: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                                believedImpactRank: number;
                                /** Format: float */
                                believedShare?: number;
                                /** @enum {string} */
                                capturedFrom: "executive_survey" | "risk_register" | "committee_minute" | "workshop";
                                /** Format: date-time */
                                capturedAt?: string;
                                /**
                                 * Format: float
                                 * @description Stated confidence that internal controls would detect this threat class
                                 */
                                trustInInternalControls?: number;
                            }[];
                            investments?: {
                                /** @enum {string} */
                                domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                                /** @enum {string} */
                                threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                                amount: {
                                    /** Format: double */
                                    amount: number;
                                    /** @example EUR */
                                    currency: string;
                                };
                                /** Format: float */
                                effortFullTimeEquivalents?: number;
                                period: string;
                                sourceSystem?: string;
                            }[];
                            divergences?: {
                                threatClass?: string;
                                /** Format: float */
                                believedImpactShare?: number;
                                /** Format: float */
                                actualInvestmentShare?: number;
                                /** Format: float */
                                divergencePoints?: number;
                                findingId?: string;
                            }[];
                            standingFindingRaised?: boolean;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recordImpactBelief: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    threatClass: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                    believedImpactRank: number;
                    /** Format: float */
                    believedShare?: number;
                    /** @enum {string} */
                    capturedFrom: "executive_survey" | "risk_register" | "committee_minute" | "workshop";
                    /** Format: date-time */
                    capturedAt?: string;
                    /**
                     * Format: float
                     * @description Stated confidence that internal controls would detect this threat class
                     */
                    trustInInternalControls?: number;
                };
            };
        };
        responses: {
            /** @description Impact belief recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @enum {string} */
                            threatClass: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain";
                            believedImpactRank: number;
                            /** Format: float */
                            believedShare?: number;
                            /** @enum {string} */
                            capturedFrom: "executive_survey" | "risk_register" | "committee_minute" | "workshop";
                            /** Format: date-time */
                            capturedAt?: string;
                            /**
                             * Format: float
                             * @description Stated confidence that internal controls would detect this threat class
                             */
                            trustInInternalControls?: number;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
