/**
 * Handlers for ImpactBelief
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AllocationDomainModule } from "../dependencies/allocation-ddd.dependencies.js";
import type { RecordImpactBeliefInput } from "@vouchstone/services/allocation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/allocation/impact-beliefs
 * Operation: recordImpactBelief
 */
export async function recordImpactBelief(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AllocationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordImpactBeliefInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.impactBeliefs.get.execute(input);
  return reply.code(201).send(result);
}


