/**
 * ExecuteUpdateRemediationCommitment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateRemediationCommitment Use Case
 *
 * DDD: Application use case for update Remediation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateRemediationCommitmentInput, UpdateRemediationCommitmentOutput } from "../dto/remediation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { RemediationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateRemediationCommitment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly remediation: RemediationRepository
  ) {}

  async execute(input: UpdateRemediationCommitmentInput): Promise<UpdateRemediationCommitmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fndId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).findingId) {
      throw new ValidationError("findingId is required");
    }
    const findingId = (input as any).findingId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.remediation.updateRemediationCommitment({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateRemediationCommitmentOutput;
  }
}
