/**
 * ExecuteRaiseFinding - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRaiseFinding Use Case
 *
 * DDD: Application use case for get Finding.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RaiseFindingInput, RaiseFindingOutput } from "../dto/finding.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { FindingRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRaiseFinding {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly finding: FindingRepository
  ) {}

  async execute(input: RaiseFindingInput): Promise<RaiseFindingOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fndId();

    // All field names extracted from OpenAPI spec: assetIds, description, domains, dueDate, origin, ownerId, severity, title
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).ownerId) {
      throw new ValidationError("ownerId is required");
    }
    const ownerId = (input as any).ownerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.finding.raiseFinding({ ownerId: ownerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${ownerId}`);
    }

    return entity as RaiseFindingOutput;
  }
}
