/**
 * Repository interface for Setting
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SettingEntity
} from "../models/setting.entity.js";
import type {
  UpdateGovernanceSettingsRequestInput
} from "../types/index.js";
/**
 * SettingRepository Interface
 */
export interface SettingRepository extends UpdateReadRepository<SettingEntity, UpdateGovernanceSettingsRequestInput, string, Record<string, never>> {

}
