/**
 * Finding Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { FindingEntity } from "@vouchstone/core/findings/models/index.js";
import { findingsSchemas } from "@vouchstone/core/findings";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "fnd";

export function createFinding(overrides: Partial<FindingEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dueDate: overrides.dueDate ?? new Date().toISOString(),
    ownerId: overrides.ownerId ?? faker.string.uuid(),
    severity: overrides.severity ?? "low",
    state: overrides.state ?? "open",
    title: overrides.title ?? faker.lorem.sentence(),
    ...overrides,
  };

  return findingsSchemas.Finding.parse(raw);
}

export function findingBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFinding(overrides));
}
