/**
 * Handlers for Score
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DomainsDomainModule } from "../dependencies/domains-ddd.dependencies.js";
import type { GetDomainScoreInput, ListDomainScoresInput } from "@vouchstone/services/domains";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/domains/scores
 * Operation: listDomainScores
 */
export async function listDomainScores(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { asOf?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DomainsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDomainScoresInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.scores.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/domains/{domainKey}/score
 * Operation: getDomainScore
 */
export async function getDomainScore(
  request: FastifyRequest<{ Params: { domainKey: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DomainsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDomainScoreInput = {
    domainKey: request.params.domainKey,
  };
  const result = await deps.useCases.scores.get.execute(input);
  return reply.code(200).send(result);
}


