/**
 * Attribution Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/attribution.openapi.types.js";
import { schemas } from "../schemas/attribution.schemas.js";

/**
 * Entity: AttributionEntity
 * Description: Represents the Attribution domain model.
 * Source: schemas.DiscovererAttribution
 * Type: Persisted Entity (x-dynamodb)
 */
export const AttributionEntitySchema = schemas.DiscovererAttribution;
export type AttributionEntity = components["schemas"]["DiscovererAttribution"];
