/**
 * Models barrel export - All Attribution entities
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./attribution.entity.js";
