/**
 * ReconciliationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReconciliationRepository Port
 *
 * DDD: Application port for reconciliationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAllocationReconciliationInput, GetAllocationReconciliationOutput } from "../dto/reconciliation.dto";
export interface ReconciliationRepository {
  getAllocationReconciliation(input: GetAllocationReconciliationInput): Promise<GetAllocationReconciliationOutput>;
}

export type { GetAllocationReconciliationInput, GetAllocationReconciliationOutput } from "../dto/reconciliation.dto";
