/**
 * Repository interface for Exercise
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExerciseEntity
} from "../models/exercise.entity.js";
import type {
  ListEmulationExercisesParams,
  EmulationExercise
} from "../types/index.js";
/**
 * ExerciseRepository Interface
 */
export interface ExerciseRepository extends CreateReadRepository<ExerciseEntity, EmulationExercise, string, ListEmulationExercisesParams> {

}
