/**
 * Repository interface for Outcome
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  OutcomeEntity
} from "../models/outcome.entity.js";
import type {
  EmulationExercise
} from "../types/index.js";
/**
 * OutcomeRepository Interface
 */
export interface OutcomeRepository extends CreateReadRepository<OutcomeEntity, EmulationExercise, string, Record<string, never>> {

}
