/**
 * DetectionIntervalRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DetectionIntervalRepository Port
 *
 * DDD: Application port for detectionintervalrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDetectionIntervalDistributionInput, GetDetectionIntervalDistributionOutput } from "../dto/detection-interval.dto";
export interface DetectionIntervalRepository {
  getDetectionIntervalDistribution(input: GetDetectionIntervalDistributionInput): Promise<GetDetectionIntervalDistributionOutput>;
}

export type { GetDetectionIntervalDistributionInput, GetDetectionIntervalDistributionOutput } from "../dto/detection-interval.dto";
