/**
 * DiscoveryShareRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DiscoveryShareRepository Port
 *
 * DDD: Application port for discoverysharerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetDiscoveryShareReportInput, GetDiscoveryShareReportOutput } from "../dto/discovery-share.dto";
export interface DiscoveryShareRepository {
  getDiscoveryShareReport(input: GetDiscoveryShareReportInput): Promise<GetDiscoveryShareReportOutput>;
}

export type { GetDiscoveryShareReportInput, GetDiscoveryShareReportOutput } from "../dto/discovery-share.dto";
