/**
 * Export Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/assurance.openapi.types.js";
import { schemas } from "../schemas/assurance.schemas.js";

/**
 * Entity: ExportEntity
 * Description: Represents the Export domain model.
 * Source: schemas.ExportPackage
 * Type: Persisted Entity (x-dynamodb)
 */
export const ExportEntitySchema = schemas.ExportPackage;
export type ExportEntity = components["schemas"]["ExportPackage"];
