/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/incidents/{incidentId}/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Records who discovered a confirmed successful attack. Captured at intake by the incident process,...
         * @description Records who discovered a confirmed successful attack. Captured at intake by the incident process, outside the control of the function whose share it measures.
         */
        post: operations["attributeIncidentDiscovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribution/discovery-share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Standing metric of what share of confirmed successful attacks the security function discovered it...
         * @description Standing metric of what share of confirmed successful attacks the security function discovered itself, with the remainder broken out by discoverer class.
         */
        get: operations["getDiscoveryShareReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/attribution/detection-intervals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Measured time to detect as a distribution, never a surveyed estimate or a single average.
         * @description Measured time to detect as a distribution, never a surveyed estimate or a single average.
         */
        get: operations["getDetectionIntervalDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DiscovererAttributionCreate: {
            /** @enum {string} */
            discovererClass: "security_function" | "other_employee" | "authority_or_regulator" | "external_researcher" | "supplier" | "customer" | "unknown";
            /** Format: date-time */
            discoveredAt: string;
            /** Format: date-time */
            estimatedCompromiseAt: string;
            detectionSource?: string;
            recordedBy?: string;
        };
        Incident: {
            id: string;
            /** Format: date-time */
            confirmedAt: string;
            /** @enum {string} */
            severity: "low" | "moderate" | "major" | "critical";
            targeted?: boolean;
            objectiveAchievedByAttacker?: boolean;
            affectedAssetIds?: string[];
            /** @enum {string} */
            threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain" | "unknown";
        };
        DetectionInterval: {
            incidentId?: string;
            /** Format: date-time */
            estimatedCompromiseAt?: string;
            /** Format: date-time */
            discoveredAt?: string;
            days?: number;
            /** @enum {string} */
            band?: "hours" | "days" | "weeks" | "months" | "year_or_more";
            /** @default true */
            measured: boolean;
        };
        DiscovererAttribution: {
            id: string;
            incidentId: string;
            /** @enum {string} */
            discovererClass: "security_function" | "other_employee" | "authority_or_regulator" | "external_researcher" | "supplier" | "customer" | "unknown";
            /** Format: date-time */
            discoveredAt: string;
            incident?: {
                id: string;
                /** Format: date-time */
                confirmedAt: string;
                /** @enum {string} */
                severity: "low" | "moderate" | "major" | "critical";
                targeted?: boolean;
                objectiveAchievedByAttacker?: boolean;
                affectedAssetIds?: string[];
                /** @enum {string} */
                threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain" | "unknown";
            };
            detectionInterval?: {
                incidentId?: string;
                /** Format: date-time */
                estimatedCompromiseAt?: string;
                /** Format: date-time */
                discoveredAt?: string;
                days?: number;
                /** @enum {string} */
                band?: "hours" | "days" | "weeks" | "months" | "year_or_more";
                /** @default true */
                measured: boolean;
            };
            recordedBy?: string;
            /** @default true */
            appendOnly: boolean;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        DataEnvelopeDiscovererAttribution: {
            data: {
                id: string;
                incidentId: string;
                /** @enum {string} */
                discovererClass: "security_function" | "other_employee" | "authority_or_regulator" | "external_researcher" | "supplier" | "customer" | "unknown";
                /** Format: date-time */
                discoveredAt: string;
                incident?: {
                    id: string;
                    /** Format: date-time */
                    confirmedAt: string;
                    /** @enum {string} */
                    severity: "low" | "moderate" | "major" | "critical";
                    targeted?: boolean;
                    objectiveAchievedByAttacker?: boolean;
                    affectedAssetIds?: string[];
                    /** @enum {string} */
                    threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain" | "unknown";
                };
                detectionInterval?: {
                    incidentId?: string;
                    /** Format: date-time */
                    estimatedCompromiseAt?: string;
                    /** Format: date-time */
                    discoveredAt?: string;
                    days?: number;
                    /** @enum {string} */
                    band?: "hours" | "days" | "weeks" | "months" | "year_or_more";
                    /** @default true */
                    measured: boolean;
                };
                recordedBy?: string;
                /** @default true */
                appendOnly: boolean;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        DiscoveryShareReport: {
            period?: string;
            confirmedSuccessfulAttacks?: number;
            /** Format: float */
            securityFunctionDiscoveryShare?: number;
            byDiscovererClass?: {
                discovererClass?: string;
                count?: number;
                /** Format: float */
                share?: number;
            }[];
            targetedAttacksObserved?: number;
            targetedAttacksAchievingObjective?: number;
            /** Format: float */
            successfulAttacksPerMonth?: number;
        };
        DataEnvelopeDiscoveryShareReport: {
            data: {
                period?: string;
                confirmedSuccessfulAttacks?: number;
                /** Format: float */
                securityFunctionDiscoveryShare?: number;
                byDiscovererClass?: {
                    discovererClass?: string;
                    count?: number;
                    /** Format: float */
                    share?: number;
                }[];
                targetedAttacksObserved?: number;
                targetedAttacksAchievingObjective?: number;
                /** Format: float */
                successfulAttacksPerMonth?: number;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        DetectionIntervalDistribution: {
            period?: string;
            sampleSize?: number;
            /** Format: float */
            medianDays?: number;
            /** Format: float */
            ninetiethPercentileDays?: number;
            byBand?: {
                /** @enum {string} */
                band?: "hours" | "days" | "weeks" | "months" | "year_or_more";
                count?: number;
                /** Format: float */
                share?: number;
            }[];
            /** @default true */
            estimatesExcluded: boolean;
        };
        DataEnvelopeDetectionIntervalDistribution: {
            data: {
                period?: string;
                sampleSize?: number;
                /** Format: float */
                medianDays?: number;
                /** Format: float */
                ninetiethPercentileDays?: number;
                byBand?: {
                    /** @enum {string} */
                    band?: "hours" | "days" | "weeks" | "months" | "year_or_more";
                    count?: number;
                    /** Format: float */
                    share?: number;
                }[];
                /** @default true */
                estimatesExcluded: boolean;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Idempotency key reuse with different body, or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        IncidentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attributeIncidentDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    discovererClass: "security_function" | "other_employee" | "authority_or_regulator" | "external_researcher" | "supplier" | "customer" | "unknown";
                    /** Format: date-time */
                    discoveredAt: string;
                    /** Format: date-time */
                    estimatedCompromiseAt: string;
                    detectionSource?: string;
                    recordedBy?: string;
                };
            };
        };
        responses: {
            /** @description Attribution recorded and detection interval measured */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            incidentId: string;
                            /** @enum {string} */
                            discovererClass: "security_function" | "other_employee" | "authority_or_regulator" | "external_researcher" | "supplier" | "customer" | "unknown";
                            /** Format: date-time */
                            discoveredAt: string;
                            incident?: {
                                id: string;
                                /** Format: date-time */
                                confirmedAt: string;
                                /** @enum {string} */
                                severity: "low" | "moderate" | "major" | "critical";
                                targeted?: boolean;
                                objectiveAchievedByAttacker?: boolean;
                                affectedAssetIds?: string[];
                                /** @enum {string} */
                                threatClass?: "insider" | "external_targeted" | "external_opportunistic" | "supply_chain" | "unknown";
                            };
                            detectionInterval?: {
                                incidentId?: string;
                                /** Format: date-time */
                                estimatedCompromiseAt?: string;
                                /** Format: date-time */
                                discoveredAt?: string;
                                days?: number;
                                /** @enum {string} */
                                band?: "hours" | "days" | "weeks" | "months" | "year_or_more";
                                /** @default true */
                                measured: boolean;
                            };
                            recordedBy?: string;
                            /** @default true */
                            appendOnly: boolean;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Idempotency key reuse with different body, or state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getDiscoveryShareReport: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery share report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            period?: string;
                            confirmedSuccessfulAttacks?: number;
                            /** Format: float */
                            securityFunctionDiscoveryShare?: number;
                            byDiscovererClass?: {
                                discovererClass?: string;
                                count?: number;
                                /** Format: float */
                                share?: number;
                            }[];
                            targetedAttacksObserved?: number;
                            targetedAttacksAchievingObjective?: number;
                            /** Format: float */
                            successfulAttacksPerMonth?: number;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getDetectionIntervalDistribution: {
        parameters: {
            query?: {
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detection interval distribution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            period?: string;
                            sampleSize?: number;
                            /** Format: float */
                            medianDays?: number;
                            /** Format: float */
                            ninetiethPercentileDays?: number;
                            byBand?: {
                                /** @enum {string} */
                                band?: "hours" | "days" | "weeks" | "months" | "year_or_more";
                                count?: number;
                                /** Format: float */
                                share?: number;
                            }[];
                            /** @default true */
                            estimatesExcluded: boolean;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
