/**
 * AttestPriorityAsset handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { attestPriorityAsset } from "@vouchstone/api-server/domains/assets/handlers";
import type { AssetsDDDDependencies } from "@vouchstone/api-server/domains/assets";
import { createAttestation as createAttestationEntity } from "@vouchstone/factories/assets";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vouchstone/tests/shared";
import { ASSETS_USE_CASES } from "../__factories__/use-cases.js";

describe("AttestPriorityAsset", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssetsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssetsDDDDependencies>(
      ASSETS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createAttestationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAttestPriorityAsset, "execute").mockResolvedValue(useCaseResult);

    await attestPriorityAsset(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAttestPriorityAsset.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
