/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as allocationRoutes from "../../domains/allocation/routes/index.js";
import * as assetsRoutes from "../../domains/assets/routes/index.js";
import * as assuranceRoutes from "../../domains/assurance/routes/index.js";
import * as attributionRoutes from "../../domains/attribution/routes/index.js";
import * as coverageRoutes from "../../domains/coverage/routes/index.js";
import * as domainsRoutes from "../../domains/domains/routes/index.js";
import * as evidenceRoutes from "../../domains/evidence/routes/index.js";
import * as exercisesRoutes from "../../domains/exercises/routes/index.js";
import * as findingsRoutes from "../../domains/findings/routes/index.js";
import * as governanceRoutes from "../../domains/governance/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "allocation", mod: allocationRoutes },
  { domain: "assets", mod: assetsRoutes },
  { domain: "assurance", mod: assuranceRoutes },
  { domain: "attribution", mod: attributionRoutes },
  { domain: "coverage", mod: coverageRoutes },
  { domain: "domains", mod: domainsRoutes },
  { domain: "evidence", mod: evidenceRoutes },
  { domain: "exercises", mod: exercisesRoutes },
  { domain: "findings", mod: findingsRoutes },
  { domain: "governance", mod: governanceRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
