/**
 * Routes for Finding
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listFindings, raiseFinding } from "../handlers/finding.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function findingRoutes(fastify: FastifyInstance) {
  // GET /v1/findings (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/findings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFindingsDependenciesForRequest();
        await listFindings(request, reply, deps);
      });
    }
  );


  // POST /v1/findings (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/findings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getFindingsDependenciesForRequest();
        await raiseFinding(request, reply, deps);
      });
    }
  );


}
