/**
 * ImpactBeliefRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ImpactBeliefRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ImpactBeliefRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ImpactBeliefRepository,
} from "@vouchstone/services/allocation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ImpactBeliefRepositoryDdb } from "./impact-belief-repository.ddb.js";

/**
 * ImpactBeliefRepositoryAdapter
 *
 * Implements ImpactBeliefRepository port for infrastructure layer.
 */
export class ImpactBeliefRepositoryAdapter implements ImpactBeliefRepository {
  private readonly ddb: ImpactBeliefRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ImpactBeliefRepositoryDdb(this.dynamoClient);
  }

  async recordImpactBelief(input: Parameters<ImpactBeliefRepository['recordImpactBelief']>[0]): Promise<Awaited<ReturnType<ImpactBeliefRepository['recordImpactBelief']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.recordImpactBelief(input);
  }
}
