/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./impact-belief-repository.ddb.js";
export * from "./reconciliation-repository.ddb.js";
export * from "./impact-belief-repository.adapter.js";
export * from "./reconciliation-repository.adapter.js";
