/**
 * ReconciliationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReconciliationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReconciliationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReconciliationRepository,
} from "@vouchstone/services/allocation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReconciliationRepositoryDdb } from "./reconciliation-repository.ddb.js";

/**
 * ReconciliationRepositoryAdapter
 *
 * Implements ReconciliationRepository port for infrastructure layer.
 */
export class ReconciliationRepositoryAdapter implements ReconciliationRepository {
  private readonly ddb: ReconciliationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReconciliationRepositoryDdb(this.dynamoClient);
  }

  async getAllocationReconciliation(input: Parameters<ReconciliationRepository['getAllocationReconciliation']>[0]): Promise<Awaited<ReturnType<ReconciliationRepository['getAllocationReconciliation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAllocationReconciliation(input);
  }
}
