/**
 * GetDiscoveryShare DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDiscoveryShareReportParams } from "@vouchstone/core/attribution";

export function createGetDiscoveryShareRequest(overrides: Partial<GetDiscoveryShareReportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
