/**
 * Assurance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assurance Domain Module - Composition root
 *
 * DDD: Composition root for assurance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExportRepositoryAdapter,
  StatementRepositoryAdapter,
} from "@vouchstone/adapters/assurance";
import { getIdGeneratorService } from "@vouchstone/adapters";
import type { AdapterDynamoDBClient } from "@vouchstone/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteExportAssurancePackage,
  ExecuteListAssuranceStatements,
  ExecuteSignAssuranceStatement,
} from "@vouchstone/services/assurance/usecases";
// Ports (interfaces)
import type {
  ExportRepository,
  StatementRepository,
} from "@vouchstone/services/assurance/ports";

export interface AssuranceDomainModule {
  repos: {
    exports: ExportRepository;
    statements: StatementRepository;
  };
  useCases: {
    exports: {
      list: ExecuteExportAssurancePackage;
    };
    statements: {
      get: ExecuteSignAssuranceStatement;
      list: ExecuteListAssuranceStatements;
    };
  };
}

export function buildAssuranceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssuranceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      exports?: ExportRepository;
      statements?: StatementRepository;
    } = {};

    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    obj.statements = new StatementRepositoryAdapter(dynamoClient);
    return {
      exports: obj.exports!,
      statements: obj.statements!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    exports: {
      list: new ExecuteExportAssurancePackage(executionContext, idGenerator, repos.exports),
    },
    statements: {
      get: new ExecuteSignAssuranceStatement(executionContext, idGenerator, repos.statements),
      list: new ExecuteListAssuranceStatements(executionContext, idGenerator, repos.statements),
    },
  };
  return { repos, useCases: useCases as AssuranceDomainModule["useCases"] };
}
