/**
 * AccessLog DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AccessLog DTOs
 *
 * DDD: Application DTOs for AccessLog use cases.
 */

import type { ListAccessLogParams } from "@vouchstone/core/governance/types";

export type ListAccessLogInput = ListAccessLogParams;

export type ListAccessLogOutput = {};
