/**
 * Setting DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Setting DTOs
 *
 * DDD: Application DTOs for Setting use cases.
 */

import type { UpdateGovernanceSettingsRequestInput } from "@vouchstone/core/governance/types";

export type GetGovernanceSettingsInput = {};

export type UpdateGovernanceSettingsInput = UpdateGovernanceSettingsRequestInput;

export type GetGovernanceSettingsOutput = {};

export type UpdateGovernanceSettingsOutput = {};
