/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Attribution Domain Use Cases
 * 
 * List of all use case names for the attribution domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ATTRIBUTION_USE_CASES = [
  "executeAttributeIncidentDiscovery",
  "executeGetDetectionIntervalDistribution",
  "executeGetDiscoveryShareReport"
] as const;
