/**
 * ExecuteRecordImpactBelief - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordImpactBelief Use Case
 *
 * DDD: Application use case for get ImpactBelief.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordImpactBeliefInput, RecordImpactBeliefOutput } from "../dto/impact-belief.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { ImpactBeliefRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteRecordImpactBelief {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly impactBelief: ImpactBeliefRepository
  ) {}

  async execute(input: RecordImpactBeliefInput): Promise<RecordImpactBeliefOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.alcId();

    // All field names extracted from OpenAPI spec: believedImpactRank, believedShare, capturedAt, capturedFrom, threatClass, trustInInternalControls
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.impactBelief.recordImpactBelief({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as RecordImpactBeliefOutput;
  }
}
