/**
 * ExecuteExportAssurancePackage - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExportAssurancePackage Use Case
 *
 * DDD: Application use case for list Export.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExportAssurancePackageInput, ExportAssurancePackageOutput } from "../dto/export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { ExportRepository } from "../ports";

export class ExecuteExportAssurancePackage {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportRepo: ExportRepository
  ) {}

  async execute(input: ExportAssurancePackageInput): Promise<ExportAssurancePackageOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.asrId();

    // All field names extracted from OpenAPI spec: audience, recipient
    // List entities via repository
    const result = await this.exportRepo.exportAssurancePackage({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ExportAssurancePackageOutput;
  }
}
