/**
 * ExecuteSignAssuranceStatement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSignAssuranceStatement Use Case
 *
 * DDD: Application use case for get Statement.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SignAssuranceStatementInput, SignAssuranceStatementOutput } from "../dto/statement.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { StatementRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteSignAssuranceStatement {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly statement: StatementRepository
  ) {}

  async execute(input: SignAssuranceStatementInput): Promise<SignAssuranceStatementOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.asrId();

    // All field names extracted from OpenAPI spec: claims, period, signatoryRole, signedBy
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.statement.signAssuranceStatement({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as SignAssuranceStatementOutput;
  }
}
