/**
 * ListStatement DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAssuranceStatementsParams } from "@vouchstone/core/assurance";

export function createListStatementRequest(overrides: Partial<ListAssuranceStatementsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
