/**
 * Export Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ExportEntity } from "@vouchstone/core/assurance/models/index.js";
import { assuranceSchemas } from "@vouchstone/core/assurance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "asr";

export function createExport(overrides: Partial<ExportEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    audience: overrides.audience ?? "audit_risk_committee",
    generatedAt: overrides.generatedAt ?? new Date().toISOString(),
    statementId: overrides.statementId ?? faker.string.uuid(),
    ...overrides,
  };

  return assuranceSchemas.ExportPackage.parse(raw);
}

export function exportBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createExport(overrides));
}
