/**
 * ImpactBelief Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/allocation.openapi.types.js";
import { schemas } from "../schemas/allocation.schemas.js";

/**
 * Entity: ImpactBeliefEntity
 * Description: Represents the ImpactBelief domain model.
 * Source: schemas.ImpactBelief
 * Type: Persisted Entity (x-dynamodb)
 */
export const ImpactBeliefEntitySchema = schemas.ImpactBelief;
export type ImpactBeliefEntity = components["schemas"]["ImpactBelief"];
