/**
 * SettingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SettingRepository Port
 *
 * DDD: Application port for settingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetGovernanceSettingsInput, GetGovernanceSettingsOutput, UpdateGovernanceSettingsInput, UpdateGovernanceSettingsOutput } from "../dto/setting.dto";
export interface SettingRepository {
  getGovernanceSettings(input: GetGovernanceSettingsInput): Promise<GetGovernanceSettingsOutput>;
  updateGovernanceSettings(input: UpdateGovernanceSettingsInput): Promise<UpdateGovernanceSettingsOutput>;
}

export type { GetGovernanceSettingsInput, GetGovernanceSettingsOutput, UpdateGovernanceSettingsInput, UpdateGovernanceSettingsOutput } from "../dto/setting.dto";
