/**
 * ExecuteUpdateGovernanceSettings - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateGovernanceSettings Use Case
 *
 * DDD: Application use case for update Setting.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateGovernanceSettingsInput, UpdateGovernanceSettingsOutput } from "../dto/setting.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { SettingRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateGovernanceSettings {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly setting: SettingRepository
  ) {}

  async execute(input: UpdateGovernanceSettingsInput): Promise<UpdateGovernanceSettingsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).id) {
      throw new ValidationError("id is required");
    }
    const idValue = (input as any).id;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.setting.updateGovernanceSettings({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateGovernanceSettingsOutput;
  }
}
