/**
 * ExecuteAttestPriorityAsset - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAttestPriorityAsset Use Case
 *
 * DDD: Application use case for get Attestation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AttestPriorityAssetInput, AttestPriorityAssetOutput } from "../dto/attestation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { AttestationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAttestPriorityAsset {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attestation: AttestationRepository
  ) {}

  async execute(input: AttestPriorityAssetInput): Promise<AttestPriorityAssetOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.astId();

    // All field names extracted from OpenAPI spec: attestedBy, locationConfirmed, locationCorrection, notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).assetId) {
      throw new ValidationError("assetId is required");
    }
    const assetId = (input as any).assetId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.attestation.attestPriorityAsset({ assetId: assetId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${assetId}`);
    }

    return entity as AttestPriorityAssetOutput;
  }
}
