/**
 * GetReconciliation DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAllocationReconciliationParams } from "@vouchstone/core/allocation";

export function createGetReconciliationRequest(overrides: Partial<GetAllocationReconciliationParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
