/**
 * Repository interface for ImpactBelief
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ImpactBeliefEntity
} from "../models/impact-belief.entity.js";
import type {
  ImpactBelief
} from "../types/index.js";
/**
 * ImpactBeliefRepository Interface
 */
export interface ImpactBeliefRepository extends CreateReadRepository<ImpactBeliefEntity, ImpactBelief, string, Record<string, never>> {

}
