/**
 * ClaimRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ClaimRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ClaimRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ClaimRepository,
} from "@vouchstone/services/domains";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ClaimRepositoryDdb } from "./claim-repository.ddb.js";

/**
 * ClaimRepositoryAdapter
 *
 * Implements ClaimRepository port for infrastructure layer.
 */
export class ClaimRepositoryAdapter implements ClaimRepository {
  private readonly ddb: ClaimRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ClaimRepositoryDdb(this.dynamoClient);
  }

  async proposeDomainClaim(input: Parameters<ClaimRepository['proposeDomainClaim']>[0]): Promise<Awaited<ReturnType<ClaimRepository['proposeDomainClaim']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.proposeDomainClaim(input);
  }
}
