/**
 * Exercises DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exercises Domain Module - Composition root
 *
 * DDD: Composition root for exercises domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ExerciseRepositoryAdapter,
  OutcomeRepositoryAdapter,
} from "@vouchstone/adapters/exercises";
import { getIdGeneratorService } from "@vouchstone/adapters";
import type { AdapterDynamoDBClient } from "@vouchstone/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListEmulationExercises,
  ExecuteRecordExerciseOutcome,
  ExecuteScheduleEmulationExercise,
} from "@vouchstone/services/exercises/usecases";
// Ports (interfaces)
import type {
  ExerciseRepository,
  OutcomeRepository,
} from "@vouchstone/services/exercises/ports";

export interface ExercisesDomainModule {
  repos: {
    exercises: ExerciseRepository;
    outcomes: OutcomeRepository;
  };
  useCases: {
    exercises: {
      get: ExecuteScheduleEmulationExercise;
      list: ExecuteListEmulationExercises;
    };
    outcomes: {
      get: ExecuteRecordExerciseOutcome;
    };
  };
}

export function buildExercisesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ExercisesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      exercises?: ExerciseRepository;
      outcomes?: OutcomeRepository;
    } = {};

    obj.exercises = new ExerciseRepositoryAdapter(dynamoClient);
    obj.outcomes = new OutcomeRepositoryAdapter(dynamoClient);
    return {
      exercises: obj.exercises!,
      outcomes: obj.outcomes!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    exercises: {
      get: new ExecuteScheduleEmulationExercise(executionContext, idGenerator, repos.exercises),
      list: new ExecuteListEmulationExercises(executionContext, idGenerator, repos.exercises),
    },
    outcomes: {
      get: new ExecuteRecordExerciseOutcome(executionContext, idGenerator, repos.outcomes),
    },
  };
  return { repos, useCases: useCases as ExercisesDomainModule["useCases"] };
}
