/**
 * ExerciseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExerciseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ExerciseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ExerciseRepository,
} from "@vouchstone/services/exercises";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ExerciseRepositoryDdb } from "./exercise-repository.ddb.js";

/**
 * ExerciseRepositoryAdapter
 *
 * Implements ExerciseRepository port for infrastructure layer.
 */
export class ExerciseRepositoryAdapter implements ExerciseRepository {
  private readonly ddb: ExerciseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ExerciseRepositoryDdb(this.dynamoClient);
  }

  async listEmulationExercises(input: Parameters<ExerciseRepository['listEmulationExercises']>[0]): Promise<Awaited<ReturnType<ExerciseRepository['listEmulationExercises']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEmulationExercises(input);
  }

  async scheduleEmulationExercise(input: Parameters<ExerciseRepository['scheduleEmulationExercise']>[0]): Promise<Awaited<ReturnType<ExerciseRepository['scheduleEmulationExercise']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.scheduleEmulationExercise(input);
  }
}
