/**
 * GetScore DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDomainScoreParams } from "@vouchstone/core/domains";

export function createGetScoreRequest(overrides: Partial<GetDomainScoreParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
