/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence Items */
        get: operations["listEvidenceItems"];
        put?: never;
        /**
         * Submit typed evidence. The validity period is derived from the committee-owned rule for the evide...
         * @description Submit typed evidence. The validity period is derived from the committee-owned rule for the evidence type and cannot be set by the submitter.
         */
        post: operations["submitEvidenceItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence/expiry-forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forward view of evidence lapsing in the requested horizon and the score impact of each lapse.
         * @description Forward view of evidence lapsing in the requested horizon and the score impact of each lapse.
         */
        get: operations["getEvidenceExpiryForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DomainKey: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
        EvidenceItem: {
            id: string;
            typeKey: string;
            domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
            assetIds?: string[];
            /** Format: date */
            effectiveDate: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @enum {string} */
            validity: "valid" | "expiring" | "expired" | "superseded";
            /** @enum {string} */
            provenance?: "internal" | "independent_provider" | "regulator" | "supplier" | "auditor";
            providerName?: string;
            artefactReference?: string;
            supersededById?: string;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ListEnvelopeEvidenceItem: {
            data: {
                items: {
                    id: string;
                    typeKey: string;
                    domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                    assetIds?: string[];
                    /** Format: date */
                    effectiveDate: string;
                    /** Format: date-time */
                    expiresAt?: string;
                    /** @enum {string} */
                    validity: "valid" | "expiring" | "expired" | "superseded";
                    /** @enum {string} */
                    provenance?: "internal" | "independent_provider" | "regulator" | "supplier" | "auditor";
                    providerName?: string;
                    artefactReference?: string;
                    supersededById?: string;
                }[];
                nextCursor?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        EvidenceItemCreate: {
            typeKey: string;
            domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
            assetIds?: string[];
            /** Format: date */
            effectiveDate: string;
            /** @enum {string} */
            provenance: "internal" | "independent_provider" | "regulator" | "supplier" | "auditor";
            providerName?: string;
            artefactReference?: string;
        };
        DataEnvelopeEvidenceItem: {
            data: {
                id: string;
                typeKey: string;
                domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                assetIds?: string[];
                /** Format: date */
                effectiveDate: string;
                /** Format: date-time */
                expiresAt?: string;
                /** @enum {string} */
                validity: "valid" | "expiring" | "expired" | "superseded";
                /** @enum {string} */
                provenance?: "internal" | "independent_provider" | "regulator" | "supplier" | "auditor";
                providerName?: string;
                artefactReference?: string;
                supersededById?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        EvidenceExpiryForecast: {
            horizonDays?: number;
            /** Format: date-time */
            generatedAt?: string;
            lapses?: {
                evidenceItemId?: string;
                typeKey?: string;
                /** Format: date-time */
                expiresAt?: string;
                affectedDomains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                projectedCapAfterLapse?: number;
            }[];
            /** Format: float */
            projectedOverallScoreChange?: number;
        };
        DataEnvelopeEvidenceExpiryForecast: {
            data: {
                horizonDays?: number;
                /** Format: date-time */
                generatedAt?: string;
                lapses?: {
                    evidenceItemId?: string;
                    typeKey?: string;
                    /** Format: date-time */
                    expiresAt?: string;
                    affectedDomains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                    projectedCapAfterLapse?: number;
                }[];
                /** Format: float */
                projectedOverallScoreChange?: number;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Semantically invalid request (e.g. PACK_EMPTY) */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque pagination cursor from a previous page. */
        Cursor: string;
        /** @description Page size (1–200). */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEvidenceItems: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous page. */
                cursor?: string;
                /** @description Page size (1–200). */
                limit?: number;
                domain?: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                validity?: "valid" | "expiring" | "expired" | "superseded";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence items page with validity state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                typeKey: string;
                                domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                                assetIds?: string[];
                                /** Format: date */
                                effectiveDate: string;
                                /** Format: date-time */
                                expiresAt?: string;
                                /** @enum {string} */
                                validity: "valid" | "expiring" | "expired" | "superseded";
                                /** @enum {string} */
                                provenance?: "internal" | "independent_provider" | "regulator" | "supplier" | "auditor";
                                providerName?: string;
                                artefactReference?: string;
                                supersededById?: string;
                            }[];
                            nextCursor?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    submitEvidenceItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    typeKey: string;
                    domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                    assetIds?: string[];
                    /** Format: date */
                    effectiveDate: string;
                    /** @enum {string} */
                    provenance: "internal" | "independent_provider" | "regulator" | "supplier" | "auditor";
                    providerName?: string;
                    artefactReference?: string;
                };
            };
        };
        responses: {
            /** @description Evidence accepted with a derived expiry */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            typeKey: string;
                            domains: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                            assetIds?: string[];
                            /** Format: date */
                            effectiveDate: string;
                            /** Format: date-time */
                            expiresAt?: string;
                            /** @enum {string} */
                            validity: "valid" | "expiring" | "expired" | "superseded";
                            /** @enum {string} */
                            provenance?: "internal" | "independent_provider" | "regulator" | "supplier" | "auditor";
                            providerName?: string;
                            artefactReference?: string;
                            supersededById?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Semantically invalid request (e.g. PACK_EMPTY) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getEvidenceExpiryForecast: {
        parameters: {
            query?: {
                horizonDays?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expiry forecast with projected score impact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            horizonDays?: number;
                            /** Format: date-time */
                            generatedAt?: string;
                            lapses?: {
                                evidenceItemId?: string;
                                typeKey?: string;
                                /** Format: date-time */
                                expiresAt?: string;
                                affectedDomains?: ("risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment")[];
                                projectedCapAfterLapse?: number;
                            }[];
                            /** Format: float */
                            projectedOverallScoreChange?: number;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
