/**
 * ExecuteSubmitEvidenceItem - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitEvidenceItem Use Case
 *
 * DDD: Application use case for create Evidence.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitEvidenceItemInput, SubmitEvidenceItemOutput } from "../dto/evidence.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { EvidenceRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSubmitEvidenceItem {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly evidence: EvidenceRepository
  ) {}

  async execute(input: SubmitEvidenceItemInput): Promise<SubmitEvidenceItemOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.evdId();

    // All field names extracted from OpenAPI spec: artefactReference, assetIds, domains, effectiveDate, provenance, providerName, typeKey
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.domains) {
      throw new ValidationError("domains is required");
    }
    if (!input.provenance) {
      throw new ValidationError("provenance is required");
    }
    if (!input.typeKey) {
      throw new ValidationError("typeKey is required");
    }
    if (!input.effectiveDate) {
      throw new ValidationError("effectiveDate is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (evidence domain)
    const entityId = this.idGenerator.evdId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.evidence.submitEvidenceItem({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitEvidenceItemOutput;
  }
}
