/**
 * ImpactBelief DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ImpactBelief DTOs
 *
 * DDD: Application DTOs for ImpactBelief use cases.
 */

import type { RecordImpactBeliefRequestInput } from "@vouchstone/core/allocation/types";

export type RecordImpactBeliefInput = RecordImpactBeliefRequestInput;

export type RecordImpactBeliefOutput = {};
