/**
 * Reconciliation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reconciliation DTOs
 *
 * DDD: Application DTOs for Reconciliation use cases.
 */

import type { GetAllocationReconciliationParams } from "@vouchstone/core/allocation/types";

export type GetAllocationReconciliationInput = GetAllocationReconciliationParams;

export type GetAllocationReconciliationOutput = {};
