/**
 * Handlers for Export
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssuranceDomainModule } from "../dependencies/assurance-ddd.dependencies.js";
import type { ExportAssurancePackageInput } from "@vouchstone/services/assurance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/assurance/statements/{statementId}/exports
 * Operation: exportAssurancePackage
 */
export async function exportAssurancePackage(
  request: FastifyRequest<{ Params: { statementId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssuranceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExportAssurancePackageInput = {
    statementId: request.params.statementId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exports.list.execute(input);
  return reply.code(201).send(result);
}


