/**
 * Handlers for Statement
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssuranceDomainModule } from "../dependencies/assurance-ddd.dependencies.js";
import type { ListAssuranceStatementsInput, SignAssuranceStatementInput } from "@vouchstone/services/assurance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/assurance/statements
 * Operation: listAssuranceStatements
 */
export async function listAssuranceStatements(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AssuranceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAssuranceStatementsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.statements.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/assurance/statements
 * Operation: signAssuranceStatement
 */
export async function signAssuranceStatement(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AssuranceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SignAssuranceStatementInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.statements.get.execute(input);
  return reply.code(201).send(result);
}


