/**
 * Allocation DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Allocation Domain Module - Composition root
 *
 * DDD: Composition root for allocation domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ImpactBeliefRepositoryAdapter,
  ReconciliationRepositoryAdapter,
} from "@vouchstone/adapters/allocation";
import { getIdGeneratorService } from "@vouchstone/adapters";
import type { AdapterDynamoDBClient } from "@vouchstone/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteRecordImpactBelief,
} from "@vouchstone/services/allocation/usecases";
// Ports (interfaces)
import type {
  ImpactBeliefRepository,
  ReconciliationRepository,
} from "@vouchstone/services/allocation/ports";

export interface AllocationDomainModule {
  repos: {
    impactBeliefs: ImpactBeliefRepository;
    reconciliations: ReconciliationRepository;
  };
  useCases: {
    impactBeliefs: {
      get: ExecuteRecordImpactBelief;
    };
  };
}

export function buildAllocationDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AllocationDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      impactBeliefs?: ImpactBeliefRepository;
      reconciliations?: ReconciliationRepository;
    } = {};

    obj.impactBeliefs = new ImpactBeliefRepositoryAdapter(dynamoClient);
    obj.reconciliations = new ReconciliationRepositoryAdapter(dynamoClient);
    return {
      impactBeliefs: obj.impactBeliefs!,
      reconciliations: obj.reconciliations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    impactBeliefs: {
      get: new ExecuteRecordImpactBelief(executionContext, idGenerator, repos.impactBeliefs),
    },
  };
  return { repos, useCases: useCases as AllocationDomainModule["useCases"] };
}
