/**
 * ExerciseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExerciseRepository Port
 *
 * DDD: Application port for exerciserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListEmulationExercisesInput, ListEmulationExercisesOutput, ScheduleEmulationExerciseInput, ScheduleEmulationExerciseOutput } from "../dto/exercise.dto";
export interface ExerciseRepository {
  listEmulationExercises(input: ListEmulationExercisesInput): Promise<ListEmulationExercisesOutput>;
  scheduleEmulationExercise(input: ScheduleEmulationExerciseInput): Promise<ScheduleEmulationExerciseOutput>;
}

export type { ListEmulationExercisesInput, ListEmulationExercisesOutput, ScheduleEmulationExerciseInput, ScheduleEmulationExerciseOutput } from "../dto/exercise.dto";
