/**
 * OutcomeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * OutcomeRepository Port
 *
 * DDD: Application port for outcomerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RecordExerciseOutcomeInput, RecordExerciseOutcomeOutput } from "../dto/outcome.dto";
export interface OutcomeRepository {
  recordExerciseOutcome(input: RecordExerciseOutcomeInput): Promise<RecordExerciseOutcomeOutput>;
}

export type { RecordExerciseOutcomeInput, RecordExerciseOutcomeOutput } from "../dto/outcome.dto";
