/**
 * Exercises Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const scheduleEmulationExercise_Body = z
  .object({
    dueDate: z.string(),
    providerName: z.string(),
    providerIndependent: z.boolean().optional().default(true),
    scopeAssetIds: z.array(z.string()),
    scenario: z.enum([
      'insider_privilege_abuse',
      'determined_external_adversary',
      'supply_chain_entry',
      'ransomware_resilience',
      'data_exfiltration',
    ]),
  })
  .passthrough();
const recordExerciseOutcome_Body = z
  .object({
    outcome: z.enum([
      'objectives_blocked',
      'partially_blocked',
      'objectives_achieved',
      'inconclusive',
    ]),
    executedAt: z.string().datetime({ offset: true }),
    detectedByDefenders: z.boolean().optional(),
    timeToDetectHours: z.number().optional(),
    findings: z
      .array(
        z
          .object({
            title: z.string(),
            description: z.string().optional(),
            severity: z.enum(['low', 'medium', 'high', 'critical']),
            domains: z.array(
              z.enum([
                'risk_exposure',
                'governance_and_leadership',
                'strategic_context',
                'resilience',
                'response_capability',
                'extended_ecosystem',
                'efficient_investment',
              ])
            ),
            assetIds: z.array(z.string()).optional(),
            ownerId: z.string(),
            dueDate: z.string(),
            origin: z
              .enum([
                'exercise',
                'incident',
                'evidence_lapse',
                'audit',
                'allocation_divergence',
                'coverage_gap',
              ])
              .optional(),
          })
          .passthrough()
      )
      .optional(),
    reportReference: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  scheduleEmulationExercise_Body,
  recordExerciseOutcome_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/exercises',
    alias: 'listEmulationExercises',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['scheduled', 'executed', 'deferred', 'missed', 'expired'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  id: z.string(),
                  status: z.enum([
                    'scheduled',
                    'executed',
                    'deferred',
                    'missed',
                    'expired',
                  ]),
                  dueDate: z.string(),
                  executedAt: z.string().datetime({ offset: true }).optional(),
                  providerName: z.string().optional(),
                  providerIndependent: z.boolean().optional(),
                  scopeAssetIds: z.array(z.string()).optional(),
                  scenario: z
                    .enum([
                      'insider_privilege_abuse',
                      'determined_external_adversary',
                      'supply_chain_entry',
                      'ransomware_resilience',
                      'data_exfiltration',
                    ])
                    .optional(),
                  outcome: z
                    .enum([
                      'objectives_blocked',
                      'partially_blocked',
                      'objectives_achieved',
                      'inconclusive',
                    ])
                    .optional(),
                  detectedByDefenders: z.boolean().optional(),
                  findingIds: z.array(z.string()).optional(),
                  evidenceItemId: z.string().optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/exercises',
    alias: 'scheduleEmulationExercise',
    description: `Schedule an independent adversary emulation with a defined scope over named priority assets. A missed due date expires the associated evidence.`,
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: scheduleEmulationExercise_Body,
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            status: z.enum([
              'scheduled',
              'executed',
              'deferred',
              'missed',
              'expired',
            ]),
            dueDate: z.string(),
            executedAt: z.string().datetime({ offset: true }).optional(),
            providerName: z.string().optional(),
            providerIndependent: z.boolean().optional(),
            scopeAssetIds: z.array(z.string()).optional(),
            scenario: z
              .enum([
                'insider_privilege_abuse',
                'determined_external_adversary',
                'supply_chain_entry',
                'ransomware_resilience',
                'data_exfiltration',
              ])
              .optional(),
            outcome: z
              .enum([
                'objectives_blocked',
                'partially_blocked',
                'objectives_achieved',
                'inconclusive',
              ])
              .optional(),
            detectedByDefenders: z.boolean().optional(),
            findingIds: z.array(z.string()).optional(),
            evidenceItemId: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/exercises/:exerciseId/outcome',
    alias: 'recordExerciseOutcome',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: recordExerciseOutcome_Body,
      },
      {
        name: 'exerciseId',
        type: 'Path',
        schema: z.string(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            id: z.string(),
            status: z.enum([
              'scheduled',
              'executed',
              'deferred',
              'missed',
              'expired',
            ]),
            dueDate: z.string(),
            executedAt: z.string().datetime({ offset: true }).optional(),
            providerName: z.string().optional(),
            providerIndependent: z.boolean().optional(),
            scopeAssetIds: z.array(z.string()).optional(),
            scenario: z
              .enum([
                'insider_privilege_abuse',
                'determined_external_adversary',
                'supply_chain_entry',
                'ransomware_resilience',
                'data_exfiltration',
              ])
              .optional(),
            outcome: z
              .enum([
                'objectives_blocked',
                'partially_blocked',
                'objectives_achieved',
                'inconclusive',
              ])
              .optional(),
            detectedByDefenders: z.boolean().optional(),
            findingIds: z.array(z.string()).optional(),
            evidenceItemId: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios('https://api.vouchstone.local', endpoints);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
