/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Allocation Domain Use Cases
 * 
 * List of all use case names for the allocation domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ALLOCATION_USE_CASES = [
  "executeGetAllocationReconciliation",
  "executeRecordImpactBelief"
] as const;
