/**
 * AssetRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssetRepository Port
 *
 * DDD: Application port for assetrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListPriorityAssetsInput, ListPriorityAssetsOutput, RegisterPriorityAssetInput, RegisterPriorityAssetOutput } from "../dto/asset.dto";
export interface AssetRepository {
  listPriorityAssets(input: ListPriorityAssetsInput): Promise<ListPriorityAssetsOutput>;
  registerPriorityAsset(input: RegisterPriorityAssetInput): Promise<RegisterPriorityAssetOutput>;
}

export type { ListPriorityAssetsInput, ListPriorityAssetsOutput, RegisterPriorityAssetInput, RegisterPriorityAssetOutput } from "../dto/asset.dto";
