/**
 * AttestationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttestationRepository Port
 *
 * DDD: Application port for attestationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AttestPriorityAssetInput, AttestPriorityAssetOutput } from "../dto/attestation.dto";
export interface AttestationRepository {
  attestPriorityAsset(input: AttestPriorityAssetInput): Promise<AttestPriorityAssetOutput>;
}

export type { AttestPriorityAssetInput, AttestPriorityAssetOutput } from "../dto/attestation.dto";
