/**
 * ImpactBelief Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ImpactBeliefEntity } from "@vouchstone/core/allocation/models/index.js";
import { allocationSchemas } from "@vouchstone/core/allocation";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "alc";

export function createImpactBelief(overrides: Partial<ImpactBeliefEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    believedImpactRank: overrides.believedImpactRank ?? faker.number.int(),
    capturedFrom: overrides.capturedFrom ?? "executive_survey",
    threatClass: overrides.threatClass ?? "insider",
    ...overrides,
  };

  return allocationSchemas.ImpactBelief.parse(raw);
}

export function impactBeliefBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createImpactBelief(overrides));
}
