/**
 * Domains DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Domains Domain Module - Composition root
 *
 * DDD: Composition root for domains domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ClaimRepositoryAdapter,
  ScoreRepositoryAdapter,
} from "@vouchstone/adapters/domains";
import { getIdGeneratorService } from "@vouchstone/adapters";
import type { AdapterDynamoDBClient } from "@vouchstone/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetDomainScore,
  ExecuteListDomainScores,
} from "@vouchstone/services/domains/usecases";
// Ports (interfaces)
import type {
  ClaimRepository,
  ScoreRepository,
} from "@vouchstone/services/domains/ports";

export interface DomainsDomainModule {
  repos: {
    claims: ClaimRepository;
    scores: ScoreRepository;
  };
  useCases: {
    scores: {
      get: ExecuteGetDomainScore;
      list: ExecuteListDomainScores;
    };
  };
}

export function buildDomainsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DomainsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      claims?: ClaimRepository;
      scores?: ScoreRepository;
    } = {};

    obj.claims = new ClaimRepositoryAdapter(dynamoClient);
    obj.scores = new ScoreRepositoryAdapter(dynamoClient);
    return {
      claims: obj.claims!,
      scores: obj.scores!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    scores: {
      get: new ExecuteGetDomainScore(executionContext, idGenerator, repos.scores),
      list: new ExecuteListDomainScores(executionContext, idGenerator, repos.scores),
    },
  };
  return { repos, useCases: useCases as DomainsDomainModule["useCases"] };
}
