/**
 * AttributionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttributionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AttributionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AttributionRepository,
} from "@vouchstone/services/attribution";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AttributionRepositoryDdb } from "./attribution-repository.ddb.js";

/**
 * AttributionRepositoryAdapter
 *
 * Implements AttributionRepository port for infrastructure layer.
 */
export class AttributionRepositoryAdapter implements AttributionRepository {
  private readonly ddb: AttributionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AttributionRepositoryDdb(this.dynamoClient);
  }

  async attributeIncidentDiscovery(input: Parameters<AttributionRepository['attributeIncidentDiscovery']>[0]): Promise<Awaited<ReturnType<AttributionRepository['attributeIncidentDiscovery']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.attributeIncidentDiscovery(input);
  }
}
