/**
 * DiscoveryShareRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DiscoveryShareRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DiscoveryShareRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DiscoveryShareRepository,
} from "@vouchstone/services/attribution";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DiscoveryShareRepositoryDdb } from "./discovery-share-repository.ddb.js";

/**
 * DiscoveryShareRepositoryAdapter
 *
 * Implements DiscoveryShareRepository port for infrastructure layer.
 */
export class DiscoveryShareRepositoryAdapter implements DiscoveryShareRepository {
  private readonly ddb: DiscoveryShareRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DiscoveryShareRepositoryDdb(this.dynamoClient);
  }

  async getDiscoveryShareReport(input: Parameters<DiscoveryShareRepository['getDiscoveryShareReport']>[0]): Promise<Awaited<ReturnType<DiscoveryShareRepository['getDiscoveryShareReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDiscoveryShareReport(input);
  }
}
