/**
 * Attribution DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attribution Domain Module - Composition root
 *
 * DDD: Composition root for attribution domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AttributionRepositoryAdapter,
  DetectionIntervalRepositoryAdapter,
  DiscoveryShareRepositoryAdapter,
} from "@vouchstone/adapters/attribution";
import { getIdGeneratorService } from "@vouchstone/adapters";
import type { AdapterDynamoDBClient } from "@vouchstone/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAttributeIncidentDiscovery,
} from "@vouchstone/services/attribution/usecases";
// Ports (interfaces)
import type {
  AttributionRepository,
  DetectionIntervalRepository,
  DiscoveryShareRepository,
} from "@vouchstone/services/attribution/ports";

export interface AttributionDomainModule {
  repos: {
    attributions: AttributionRepository;
    detectionIntervals: DetectionIntervalRepository;
    discoveryShares: DiscoveryShareRepository;
  };
  useCases: {
    attributions: {
      get: ExecuteAttributeIncidentDiscovery;
    };
  };
}

export function buildAttributionDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AttributionDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      attributions?: AttributionRepository;
      detectionIntervals?: DetectionIntervalRepository;
      discoveryShares?: DiscoveryShareRepository;
    } = {};

    obj.attributions = new AttributionRepositoryAdapter(dynamoClient);
    obj.detectionIntervals = new DetectionIntervalRepositoryAdapter(dynamoClient);
    obj.discoveryShares = new DiscoveryShareRepositoryAdapter(dynamoClient);
    return {
      attributions: obj.attributions!,
      detectionIntervals: obj.detectionIntervals!,
      discoveryShares: obj.discoveryShares!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    attributions: {
      get: new ExecuteAttributeIncidentDiscovery(executionContext, idGenerator, repos.attributions),
    },
  };
  return { repos, useCases: useCases as AttributionDomainModule["useCases"] };
}
