/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@vouchstone/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@vouchstone/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@vouchstone/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _allocation from "./allocation/index.js";
import * as _assets from "./assets/index.js";
import * as _assurance from "./assurance/index.js";
import * as _attribution from "./attribution/index.js";
import * as _coverage from "./coverage/index.js";
import * as _domains from "./domains/index.js";
import * as _evidence from "./evidence/index.js";
import * as _exercises from "./exercises/index.js";
import * as _findings from "./findings/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";

// Export as namespaces
export const allocation = _allocation;
export const assets = _assets;
export const assurance = _assurance;
export const attribution = _attribution;
export const coverage = _coverage;
export const domains = _domains;
export const evidence = _evidence;
export const exercises = _exercises;
export const findings = _findings;
export const governance = _governance;
export const identity = _identity;
