/**
 * ExecuteListDomainScores - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDomainScores Use Case
 *
 * DDD: Application use case for list Score.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDomainScoresInput, ListDomainScoresOutput } from "../dto/score.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { ScoreRepository } from "../ports";

export class ExecuteListDomainScores {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly score: ScoreRepository
  ) {}

  async execute(input: ListDomainScoresInput): Promise<ListDomainScoresOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.domId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.score.listDomainScores({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDomainScoresOutput;
  }
}
