/**
 * ListEmulationExercises handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listEmulationExercises } from "@vouchstone/api-server/domains/exercises/handlers";
import type { ExercisesDDDDependencies } from "@vouchstone/api-server/domains/exercises";
import { createExercise as createExerciseEntity } from "@vouchstone/factories/exercises";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vouchstone/tests/shared";
import { EXERCISES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListEmulationExercises", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ExercisesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ExercisesDDDDependencies>(
      EXERCISES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createExerciseEntity({ orgId }),
      createExerciseEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListEmulationExercises, "execute").mockResolvedValue(useCaseResult);

    await listEmulationExercises(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListEmulationExercises.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
