/**
 * ScheduleEmulationExercise handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { scheduleEmulationExercise } from "@vouchstone/api-server/domains/exercises/handlers";
import type { ExercisesDDDDependencies } from "@vouchstone/api-server/domains/exercises";
import { createExercise as createExerciseEntity } from "@vouchstone/factories/exercises";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vouchstone/tests/shared";
import { EXERCISES_USE_CASES } from "../__factories__/use-cases.js";

describe("ScheduleEmulationExercise", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ExercisesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ExercisesDDDDependencies>(
      EXERCISES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createExerciseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeScheduleEmulationExercise, "execute").mockResolvedValue(useCaseResult);

    await scheduleEmulationExercise(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeScheduleEmulationExercise.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
