/**
 * Handlers for Setting
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { GetGovernanceSettingsInput, UpdateGovernanceSettingsInput } from "@vouchstone/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/governance/settings
 * Operation: getGovernanceSettings
 */
export async function getGovernanceSettings(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetGovernanceSettingsInput = {};
  const result = await deps.useCases.settings.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/governance/settings
 * Operation: updateGovernanceSettings
 */
export async function updateGovernanceSettings(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateGovernanceSettingsInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.settings.update.execute(input);
  return reply.code(200).send(result);
}


