/**
 * GetAllocationReconciliation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: allocation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAllocationReconciliation } from "@vouchstone/api-server/domains/allocation/handlers";
import type { AllocationDDDDependencies } from "@vouchstone/api-server/domains/allocation";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vouchstone/tests/shared";
import { ALLOCATION_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAllocationReconciliation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AllocationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AllocationDDDDependencies>(
      ALLOCATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAllocationReconciliation, "execute").mockResolvedValue(useCaseResult);

    await getAllocationReconciliation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAllocationReconciliation.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
