/**
 * Routes for ExpiryForecast
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getEvidenceExpiryForecast } from "../handlers/expiry-forecast.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function expiryForecastRoutes(fastify: FastifyInstance) {
  // GET /v1/evidence/expiry-forecast (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/evidence/expiry-forecast",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidenceDependenciesForRequest();
        await getEvidenceExpiryForecast(request, reply, deps);
      });
    }
  );


}
