/**
 * EvidenceRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EvidenceRepository Port
 *
 * DDD: Application port for evidencerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListEvidenceItemsInput, ListEvidenceItemsOutput, SubmitEvidenceItemInput, SubmitEvidenceItemOutput } from "../dto/evidence.dto";
export interface EvidenceRepository {
  listEvidenceItems(input: ListEvidenceItemsInput): Promise<ListEvidenceItemsOutput>;
  submitEvidenceItem(input: SubmitEvidenceItemInput): Promise<SubmitEvidenceItemOutput>;
}

export type { ListEvidenceItemsInput, ListEvidenceItemsOutput, SubmitEvidenceItemInput, SubmitEvidenceItemOutput } from "../dto/evidence.dto";
