/**
 * ExpiryForecastRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExpiryForecastRepository Port
 *
 * DDD: Application port for expiryforecastrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetEvidenceExpiryForecastInput, GetEvidenceExpiryForecastOutput } from "../dto/expiry-forecast.dto";
export interface ExpiryForecastRepository {
  getEvidenceExpiryForecast(input: GetEvidenceExpiryForecastInput): Promise<GetEvidenceExpiryForecastOutput>;
}

export type { GetEvidenceExpiryForecastInput, GetEvidenceExpiryForecastOutput } from "../dto/expiry-forecast.dto";
