/**
 * Routes for Setting
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getGovernanceSettings, updateGovernanceSettings } from "../handlers/setting.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function settingRoutes(fastify: FastifyInstance) {
  // GET /v1/governance/settings (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/governance/settings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await getGovernanceSettings(request, reply, deps);
      });
    }
  );


  // PUT /v1/governance/settings (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/governance/settings",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await updateGovernanceSettings(request, reply, deps);
      });
    }
  );


}
