/**
 * Assets DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Assets Domain Module - Composition root
 *
 * DDD: Composition root for assets domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssetRepositoryAdapter,
  AttestationRepositoryAdapter,
} from "@vouchstone/adapters/assets";
import { getIdGeneratorService } from "@vouchstone/adapters";
import type { AdapterDynamoDBClient } from "@vouchstone/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAttestPriorityAsset,
  ExecuteListPriorityAssets,
  ExecuteRegisterPriorityAsset,
} from "@vouchstone/services/assets/usecases";
// Ports (interfaces)
import type {
  AssetRepository,
  AttestationRepository,
} from "@vouchstone/services/assets/ports";

export interface AssetsDomainModule {
  repos: {
    assets: AssetRepository;
    attestations: AttestationRepository;
  };
  useCases: {
    assets: {
      create: ExecuteRegisterPriorityAsset;
      list: ExecuteListPriorityAssets;
    };
    attestations: {
      get: ExecuteAttestPriorityAsset;
    };
  };
}

export function buildAssetsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssetsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assets?: AssetRepository;
      attestations?: AttestationRepository;
    } = {};

    obj.assets = new AssetRepositoryAdapter(dynamoClient);
    obj.attestations = new AttestationRepositoryAdapter(dynamoClient);
    return {
      assets: obj.assets!,
      attestations: obj.attestations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assets: {
      create: new ExecuteRegisterPriorityAsset(executionContext, idGenerator, repos.assets),
      list: new ExecuteListPriorityAssets(executionContext, idGenerator, repos.assets),
    },
    attestations: {
      get: new ExecuteAttestPriorityAsset(executionContext, idGenerator, repos.attestations),
    },
  };
  return { repos, useCases: useCases as AssetsDomainModule["useCases"] };
}
