/**
 * Repository interface for Export
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ExportEntity
} from "../models/export.entity.js";
/**
 * ExportRepository Interface
 */
export interface ExportRepository extends ReadRepository<ExportEntity, string, Record<string, never>> {

}
