/**
 * Repository interface for Statement
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  StatementEntity
} from "../models/statement.entity.js";
import type {
  ListAssuranceStatementsParams,
  AssuranceStatement
} from "../types/index.js";
/**
 * StatementRepository Interface
 */
export interface StatementRepository extends CreateReadRepository<StatementEntity, AssuranceStatement, string, ListAssuranceStatementsParams> {

}
