/**
 * Exercise Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ExerciseEntity } from "@vouchstone/core/exercises/models/index.js";
import { exercisesSchemas } from "@vouchstone/core/exercises";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "exr";

export function createExercise(overrides: Partial<ExerciseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dueDate: overrides.dueDate ?? new Date().toISOString(),
    status: overrides.status ?? "scheduled",
    ...overrides,
  };

  return exercisesSchemas.EmulationExercise.parse(raw);
}

export function exerciseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createExercise(overrides));
}
