/**
 * Remediation Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/findings.openapi.types.js";
import { schemas } from "../schemas/findings.schemas.js";

/**
 * Entity: RemediationEntity
 * Description: Represents the Remediation domain model.
 * Source: schemas.Finding
 * Type: Persisted Entity (x-dynamodb)
 */
export const RemediationEntitySchema = schemas.Finding;
export type RemediationEntity = components["schemas"]["Finding"];
