/**
 * ListExercise DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListEmulationExercisesParams } from "@vouchstone/core/exercises";

export function createListExerciseRequest(overrides: Partial<ListEmulationExercisesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
