/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/assurance/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assurance Statements */
        get: operations["listAssuranceStatements"];
        put?: never;
        /**
         * Signs and freezes the statement together with the exact evidence validity state at the moment of ...
         * @description Signs and freezes the statement together with the exact evidence validity state at the moment of publication. Immutable thereafter.
         */
        post: operations["signAssuranceStatement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/assurance/statements/{statementId}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statementId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generates the committee pack, regulatory return, or insurance proposal response from the one froz...
         * @description Generates the committee pack, regulatory return, or insurance proposal response from the one frozen evidence base, with claim-level traceability.
         */
        post: operations["exportAssurancePackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DomainKey: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
        StatementClaim: {
            /** @enum {string} */
            domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
            score: number;
            narrative?: string;
            supportingEvidenceIds?: string[];
            capAtPublication?: number;
        };
        DiscoveryShareReport: {
            period?: string;
            confirmedSuccessfulAttacks?: number;
            /** Format: float */
            securityFunctionDiscoveryShare?: number;
            byDiscovererClass?: {
                discovererClass?: string;
                count?: number;
                /** Format: float */
                share?: number;
            }[];
            targetedAttacksObserved?: number;
            targetedAttacksAchievingObjective?: number;
            /** Format: float */
            successfulAttacksPerMonth?: number;
        };
        ContractualClause: {
            /** @enum {string} */
            clauseType?: "notification_deadline" | "audit_right" | "subprocessor_control" | "recovery_obligation" | "regulatory_compliance";
            present?: boolean;
            /** Format: date */
            reviewedAt?: string;
        };
        ThirdPartyAssessment: {
            supplierId?: string;
            supplierName?: string;
            /** Format: date-time */
            assessedAt?: string;
            /** Format: date-time */
            validUntil?: string;
            crisisCollaborationTested?: boolean;
            clauses?: {
                /** @enum {string} */
                clauseType?: "notification_deadline" | "audit_right" | "subprocessor_control" | "recovery_obligation" | "regulatory_compliance";
                present?: boolean;
                /** Format: date */
                reviewedAt?: string;
            }[];
        };
        AssuranceStatement: {
            id: string;
            period: string;
            signedBy: string;
            signatoryRole?: string;
            /** Format: date-time */
            signedAt: string;
            claims?: {
                /** @enum {string} */
                domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                score: number;
                narrative?: string;
                supportingEvidenceIds?: string[];
                capAtPublication?: number;
            }[];
            /** Format: float */
            overallScore?: number;
            /** Format: float */
            evidenceBackedShare?: number;
            discoveryShare?: {
                period?: string;
                confirmedSuccessfulAttacks?: number;
                /** Format: float */
                securityFunctionDiscoveryShare?: number;
                byDiscovererClass?: {
                    discovererClass?: string;
                    count?: number;
                    /** Format: float */
                    share?: number;
                }[];
                targetedAttacksObserved?: number;
                targetedAttacksAchievingObjective?: number;
                /** Format: float */
                successfulAttacksPerMonth?: number;
            };
            extendedEcosystemAssessments?: {
                supplierId?: string;
                supplierName?: string;
                /** Format: date-time */
                assessedAt?: string;
                /** Format: date-time */
                validUntil?: string;
                crisisCollaborationTested?: boolean;
                clauses?: {
                    /** @enum {string} */
                    clauseType?: "notification_deadline" | "audit_right" | "subprocessor_control" | "recovery_obligation" | "regulatory_compliance";
                    present?: boolean;
                    /** Format: date */
                    reviewedAt?: string;
                }[];
            }[];
            frozenEvidenceStateHash?: string;
            /** @default true */
            immutable: boolean;
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        ListEnvelopeAssuranceStatement: {
            data: {
                items: {
                    id: string;
                    period: string;
                    signedBy: string;
                    signatoryRole?: string;
                    /** Format: date-time */
                    signedAt: string;
                    claims?: {
                        /** @enum {string} */
                        domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                        score: number;
                        narrative?: string;
                        supportingEvidenceIds?: string[];
                        capAtPublication?: number;
                    }[];
                    /** Format: float */
                    overallScore?: number;
                    /** Format: float */
                    evidenceBackedShare?: number;
                    discoveryShare?: {
                        period?: string;
                        confirmedSuccessfulAttacks?: number;
                        /** Format: float */
                        securityFunctionDiscoveryShare?: number;
                        byDiscovererClass?: {
                            discovererClass?: string;
                            count?: number;
                            /** Format: float */
                            share?: number;
                        }[];
                        targetedAttacksObserved?: number;
                        targetedAttacksAchievingObjective?: number;
                        /** Format: float */
                        successfulAttacksPerMonth?: number;
                    };
                    extendedEcosystemAssessments?: {
                        supplierId?: string;
                        supplierName?: string;
                        /** Format: date-time */
                        assessedAt?: string;
                        /** Format: date-time */
                        validUntil?: string;
                        crisisCollaborationTested?: boolean;
                        clauses?: {
                            /** @enum {string} */
                            clauseType?: "notification_deadline" | "audit_right" | "subprocessor_control" | "recovery_obligation" | "regulatory_compliance";
                            present?: boolean;
                            /** Format: date */
                            reviewedAt?: string;
                        }[];
                    }[];
                    frozenEvidenceStateHash?: string;
                    /** @default true */
                    immutable: boolean;
                }[];
                nextCursor?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        AssuranceStatementCreate: {
            period: string;
            claims: {
                /** @enum {string} */
                domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                score: number;
                narrative?: string;
                supportingEvidenceIds?: string[];
                capAtPublication?: number;
            }[];
            signedBy: string;
            signatoryRole?: string;
        };
        DataEnvelopeAssuranceStatement: {
            data: {
                id: string;
                period: string;
                signedBy: string;
                signatoryRole?: string;
                /** Format: date-time */
                signedAt: string;
                claims?: {
                    /** @enum {string} */
                    domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                    score: number;
                    narrative?: string;
                    supportingEvidenceIds?: string[];
                    capAtPublication?: number;
                }[];
                /** Format: float */
                overallScore?: number;
                /** Format: float */
                evidenceBackedShare?: number;
                discoveryShare?: {
                    period?: string;
                    confirmedSuccessfulAttacks?: number;
                    /** Format: float */
                    securityFunctionDiscoveryShare?: number;
                    byDiscovererClass?: {
                        discovererClass?: string;
                        count?: number;
                        /** Format: float */
                        share?: number;
                    }[];
                    targetedAttacksObserved?: number;
                    targetedAttacksAchievingObjective?: number;
                    /** Format: float */
                    successfulAttacksPerMonth?: number;
                };
                extendedEcosystemAssessments?: {
                    supplierId?: string;
                    supplierName?: string;
                    /** Format: date-time */
                    assessedAt?: string;
                    /** Format: date-time */
                    validUntil?: string;
                    crisisCollaborationTested?: boolean;
                    clauses?: {
                        /** @enum {string} */
                        clauseType?: "notification_deadline" | "audit_right" | "subprocessor_control" | "recovery_obligation" | "regulatory_compliance";
                        present?: boolean;
                        /** Format: date */
                        reviewedAt?: string;
                    }[];
                }[];
                frozenEvidenceStateHash?: string;
                /** @default true */
                immutable: boolean;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        ExportPackage: {
            id: string;
            statementId: string;
            /** @enum {string} */
            audience: "audit_risk_committee" | "sector_regulator" | "cyber_insurer" | "internal_audit";
            recipient?: string;
            /** Format: date-time */
            generatedAt: string;
            generatedBy?: string;
            manifestHash?: string;
            claimTraceability?: {
                /** @enum {string} */
                claimDomain?: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                evidenceItemIds?: string[];
            }[];
        };
        DataEnvelopeExportPackage: {
            data: {
                id: string;
                statementId: string;
                /** @enum {string} */
                audience: "audit_risk_committee" | "sector_regulator" | "cyber_insurer" | "internal_audit";
                recipient?: string;
                /** Format: date-time */
                generatedAt: string;
                generatedBy?: string;
                manifestHash?: string;
                claimTraceability?: {
                    /** @enum {string} */
                    claimDomain?: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                    evidenceItemIds?: string[];
                }[];
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Idempotency key reuse with different body, or state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Authenticated but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        StatementId: string;
        /** @description Opaque pagination cursor from a previous page. */
        Cursor: string;
        /** @description Page size (1–200). */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAssuranceStatements: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous page. */
                cursor?: string;
                /** @description Page size (1–200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assurance statements page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                period: string;
                                signedBy: string;
                                signatoryRole?: string;
                                /** Format: date-time */
                                signedAt: string;
                                claims?: {
                                    /** @enum {string} */
                                    domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                                    score: number;
                                    narrative?: string;
                                    supportingEvidenceIds?: string[];
                                    capAtPublication?: number;
                                }[];
                                /** Format: float */
                                overallScore?: number;
                                /** Format: float */
                                evidenceBackedShare?: number;
                                discoveryShare?: {
                                    period?: string;
                                    confirmedSuccessfulAttacks?: number;
                                    /** Format: float */
                                    securityFunctionDiscoveryShare?: number;
                                    byDiscovererClass?: {
                                        discovererClass?: string;
                                        count?: number;
                                        /** Format: float */
                                        share?: number;
                                    }[];
                                    targetedAttacksObserved?: number;
                                    targetedAttacksAchievingObjective?: number;
                                    /** Format: float */
                                    successfulAttacksPerMonth?: number;
                                };
                                extendedEcosystemAssessments?: {
                                    supplierId?: string;
                                    supplierName?: string;
                                    /** Format: date-time */
                                    assessedAt?: string;
                                    /** Format: date-time */
                                    validUntil?: string;
                                    crisisCollaborationTested?: boolean;
                                    clauses?: {
                                        /** @enum {string} */
                                        clauseType?: "notification_deadline" | "audit_right" | "subprocessor_control" | "recovery_obligation" | "regulatory_compliance";
                                        present?: boolean;
                                        /** Format: date */
                                        reviewedAt?: string;
                                    }[];
                                }[];
                                frozenEvidenceStateHash?: string;
                                /** @default true */
                                immutable: boolean;
                            }[];
                            nextCursor?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    signAssuranceStatement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    period: string;
                    claims: {
                        /** @enum {string} */
                        domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                        score: number;
                        narrative?: string;
                        supportingEvidenceIds?: string[];
                        capAtPublication?: number;
                    }[];
                    signedBy: string;
                    signatoryRole?: string;
                };
            };
        };
        responses: {
            /** @description Statement signed and frozen */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            period: string;
                            signedBy: string;
                            signatoryRole?: string;
                            /** Format: date-time */
                            signedAt: string;
                            claims?: {
                                /** @enum {string} */
                                domain: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                                score: number;
                                narrative?: string;
                                supportingEvidenceIds?: string[];
                                capAtPublication?: number;
                            }[];
                            /** Format: float */
                            overallScore?: number;
                            /** Format: float */
                            evidenceBackedShare?: number;
                            discoveryShare?: {
                                period?: string;
                                confirmedSuccessfulAttacks?: number;
                                /** Format: float */
                                securityFunctionDiscoveryShare?: number;
                                byDiscovererClass?: {
                                    discovererClass?: string;
                                    count?: number;
                                    /** Format: float */
                                    share?: number;
                                }[];
                                targetedAttacksObserved?: number;
                                targetedAttacksAchievingObjective?: number;
                                /** Format: float */
                                successfulAttacksPerMonth?: number;
                            };
                            extendedEcosystemAssessments?: {
                                supplierId?: string;
                                supplierName?: string;
                                /** Format: date-time */
                                assessedAt?: string;
                                /** Format: date-time */
                                validUntil?: string;
                                crisisCollaborationTested?: boolean;
                                clauses?: {
                                    /** @enum {string} */
                                    clauseType?: "notification_deadline" | "audit_right" | "subprocessor_control" | "recovery_obligation" | "regulatory_compliance";
                                    present?: boolean;
                                    /** Format: date */
                                    reviewedAt?: string;
                                }[];
                            }[];
                            frozenEvidenceStateHash?: string;
                            /** @default true */
                            immutable: boolean;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Idempotency key reuse with different body, or state conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    exportAssurancePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statementId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    audience: "audit_risk_committee" | "sector_regulator" | "cyber_insurer" | "internal_audit";
                    recipient?: string;
                };
            };
        };
        responses: {
            /** @description Export package generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            statementId: string;
                            /** @enum {string} */
                            audience: "audit_risk_committee" | "sector_regulator" | "cyber_insurer" | "internal_audit";
                            recipient?: string;
                            /** Format: date-time */
                            generatedAt: string;
                            generatedBy?: string;
                            manifestHash?: string;
                            claimTraceability?: {
                                /** @enum {string} */
                                claimDomain?: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                                evidenceItemIds?: string[];
                            }[];
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Authenticated but not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
