/**
 * Attestation Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AttestationEntity } from "@vouchstone/core/assets/models/index.js";
import { assetsSchemas } from "@vouchstone/core/assets";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ast";

export function createAttestation(overrides: Partial<AttestationEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    assetId: overrides.assetId ?? faker.string.uuid(),
    attestedAt: overrides.attestedAt ?? new Date().toISOString(),
    attestedBy: overrides.attestedBy ?? faker.lorem.word(),
    ...overrides,
  };

  return assetsSchemas.AssetAttestation.parse(raw);
}

export function attestationBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAttestation(overrides));
}
