/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Assurance Domain Use Cases
 * 
 * List of all use case names for the assurance domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const ASSURANCE_USE_CASES = [
  "executeExportAssurancePackage",
  "executeListAssuranceStatements",
  "executeSignAssuranceStatement"
] as const;
