/**
 * Repository interface for Remediation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  UpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  RemediationEntity
} from "../models/remediation.entity.js";
import type {
  UpdateRemediationCommitmentRequestInput
} from "../types/index.js";
/**
 * RemediationRepository Interface
 */
export interface RemediationRepository extends UpdateReadRepository<RemediationEntity, UpdateRemediationCommitmentRequestInput, string, Record<string, never>> {

}
