/**
 * AssetRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssetRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AssetRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AssetRepository,
} from "@vouchstone/services/assets";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AssetRepositoryDdb } from "./asset-repository.ddb.js";

/**
 * AssetRepositoryAdapter
 *
 * Implements AssetRepository port for infrastructure layer.
 */
export class AssetRepositoryAdapter implements AssetRepository {
  private readonly ddb: AssetRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AssetRepositoryDdb(this.dynamoClient);
  }

  async listPriorityAssets(input: Parameters<AssetRepository['listPriorityAssets']>[0]): Promise<Awaited<ReturnType<AssetRepository['listPriorityAssets']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPriorityAssets(input);
  }

  async registerPriorityAsset(input: Parameters<AssetRepository['registerPriorityAsset']>[0]): Promise<Awaited<ReturnType<AssetRepository['registerPriorityAsset']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerPriorityAsset(input);
  }
}
