/**
 * AttestationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AttestationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AttestationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AttestationRepository,
} from "@vouchstone/services/assets";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AttestationRepositoryDdb } from "./attestation-repository.ddb.js";

/**
 * AttestationRepositoryAdapter
 *
 * Implements AttestationRepository port for infrastructure layer.
 */
export class AttestationRepositoryAdapter implements AttestationRepository {
  private readonly ddb: AttestationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AttestationRepositoryDdb(this.dynamoClient);
  }

  async attestPriorityAsset(input: Parameters<AttestationRepository['attestPriorityAsset']>[0]): Promise<Awaited<ReturnType<AttestationRepository['attestPriorityAsset']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.attestPriorityAsset(input);
  }
}
