/**
 * Evidence Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/evidence.openapi.types.js";
import { schemas } from "../schemas/evidence.schemas.js";

/**
 * Entity: EvidenceEntity
 * Description: Represents the Evidence domain model.
 * Source: schemas.EvidenceItem
 * Type: Persisted Entity (x-dynamodb)
 */
export const EvidenceEntitySchema = schemas.EvidenceItem;
export type EvidenceEntity = components["schemas"]["EvidenceItem"];
