/**
 * Handlers for ExpiryForecast
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidenceDomainModule } from "../dependencies/evidence-ddd.dependencies.js";
import type { GetEvidenceExpiryForecastInput } from "@vouchstone/services/evidence";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/evidence/expiry-forecast
 * Operation: getEvidenceExpiryForecast
 */
export async function getEvidenceExpiryForecast(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { horizonDays?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidenceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetEvidenceExpiryForecastInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.expiryForecasts.get.execute(input);
  return reply.code(200).send(result);
}


