/**
 * Exercise DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Exercise DTOs
 *
 * DDD: Application DTOs for Exercise use cases.
 */

import type { ListEmulationExercisesParams, ScheduleEmulationExerciseRequestInput } from "@vouchstone/core/exercises/types";

export type ListEmulationExercisesInput = ListEmulationExercisesParams;

export type ScheduleEmulationExerciseInput = ScheduleEmulationExerciseRequestInput;

export type ListEmulationExercisesOutput = {};

export type ScheduleEmulationExerciseOutput = {};
