/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the assurance domain.
 * Use these factories in tests to create test data.
 */

export { createExport } from "./export/entity/export.entity.factory.js";
export { createStatement } from "./statement/entity/statement.entity.factory.js";
