/**
 * ExecuteRecordExerciseOutcome - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRecordExerciseOutcome Use Case
 *
 * DDD: Application use case for get Outcome.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RecordExerciseOutcomeInput, RecordExerciseOutcomeOutput } from "../dto/outcome.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { OutcomeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRecordExerciseOutcome {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly outcome: OutcomeRepository
  ) {}

  async execute(input: RecordExerciseOutcomeInput): Promise<RecordExerciseOutcomeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.exrId();

    // All field names extracted from OpenAPI spec: detectedByDefenders, executedAt, findings, outcome, reportReference, timeToDetectHours
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).exerciseId) {
      throw new ValidationError("exerciseId is required");
    }
    const exerciseId = (input as any).exerciseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.outcome.recordExerciseOutcome({ exerciseId: exerciseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${exerciseId}`);
    }

    return entity as RecordExerciseOutcomeOutput;
  }
}
