/**
 * ExecuteListEmulationExercises - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: exercises
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListEmulationExercises Use Case
 *
 * DDD: Application use case for list Exercise.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListEmulationExercisesInput, ListEmulationExercisesOutput } from "../dto/exercise.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vouchstone/services/_shared/index.js";
import type { ExerciseRepository } from "../ports";

export class ExecuteListEmulationExercises {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exercise: ExerciseRepository
  ) {}

  async execute(input: ListEmulationExercisesInput): Promise<ListEmulationExercisesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.exrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.exercise.listEmulationExercises({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListEmulationExercisesOutput;
  }
}
