/**
 * Asset DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Asset DTOs
 *
 * DDD: Application DTOs for Asset use cases.
 */

import type { ListPriorityAssetsParams, RegisterPriorityAssetRequestInput } from "@vouchstone/core/assets/types";

export type ListPriorityAssetsInput = ListPriorityAssetsParams;

export type RegisterPriorityAssetInput = RegisterPriorityAssetRequestInput;

export type ListPriorityAssetsOutput = {};

export type RegisterPriorityAssetOutput = {};
