/**
 * Attestation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestation DTOs
 *
 * DDD: Application DTOs for Attestation use cases.
 */

import type { AttestPriorityAssetParams, AttestPriorityAssetRequestInput } from "@vouchstone/core/assets/types";

export type AttestPriorityAssetInput = AttestPriorityAssetParams & AttestPriorityAssetRequestInput;

export type AttestPriorityAssetOutput = {};
