/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/governance/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Governance Settings */
        get: operations["getGovernanceSettings"];
        /**
         * Requires the committee scope. The scored security function cannot alter the mechanism by which it...
         * @description Requires the committee scope. The scored security function cannot alter the mechanism by which it is measured.
         */
        put: operations["updateGovernanceSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/governance/access-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reads of the asset register, coverage gaps, and exercise findings are recorded and reviewable.
         * @description Reads of the asset register, coverage gaps, and exercise findings are recorded and reviewable.
         */
        get: operations["listAccessLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ValidityRule: {
            evidenceTypeKey: string;
            validityDays: number;
            /** @description Committee approver, not the security function */
            setBy?: string;
        };
        EvidenceType: {
            /** @enum {string} */
            key: "asset_attestation" | "emulation_exercise_report" | "response_plan_test" | "recovery_plan_test" | "detection_coverage_scan" | "escalation_path_test" | "third_party_assessment" | "contractual_clause_review" | "control_spend_statement" | "training_completion" | "incident_postmortem";
            label: string;
            defaultValidityDays?: number;
        };
        /** @enum {string} */
        DomainKey: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
        Domain: {
            /** @enum {string} */
            key: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
            name: string;
            description?: string;
            /** Format: float */
            weighting?: number;
        };
        ApprovalRecord: {
            approvedBy: string;
            approverRole?: string;
            /** Format: date-time */
            approvedAt: string;
            minuteReference?: string;
            rationale?: string;
        };
        GovernanceSetting: {
            validityRules?: {
                evidenceTypeKey: string;
                validityDays: number;
                /** @description Committee approver, not the security function */
                setBy?: string;
            }[];
            evidenceTypes?: {
                /** @enum {string} */
                key: "asset_attestation" | "emulation_exercise_report" | "response_plan_test" | "recovery_plan_test" | "detection_coverage_scan" | "escalation_path_test" | "third_party_assessment" | "contractual_clause_review" | "control_spend_statement" | "training_completion" | "incident_postmortem";
                label: string;
                defaultValidityDays?: number;
            }[];
            domains?: {
                /** @enum {string} */
                key: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                name: string;
                description?: string;
                /** Format: float */
                weighting?: number;
            }[];
            capOnOpenCriticalFinding?: number;
            capOnStaleAttestation?: number;
            /** @enum {string} */
            ownedBy?: "audit_risk_committee";
            lastApproval?: {
                approvedBy: string;
                approverRole?: string;
                /** Format: date-time */
                approvedAt: string;
                minuteReference?: string;
                rationale?: string;
            };
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        DataEnvelopeGovernanceSetting: {
            data: {
                validityRules?: {
                    evidenceTypeKey: string;
                    validityDays: number;
                    /** @description Committee approver, not the security function */
                    setBy?: string;
                }[];
                evidenceTypes?: {
                    /** @enum {string} */
                    key: "asset_attestation" | "emulation_exercise_report" | "response_plan_test" | "recovery_plan_test" | "detection_coverage_scan" | "escalation_path_test" | "third_party_assessment" | "contractual_clause_review" | "control_spend_statement" | "training_completion" | "incident_postmortem";
                    label: string;
                    defaultValidityDays?: number;
                }[];
                domains?: {
                    /** @enum {string} */
                    key: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                    name: string;
                    description?: string;
                    /** Format: float */
                    weighting?: number;
                }[];
                capOnOpenCriticalFinding?: number;
                capOnStaleAttestation?: number;
                /** @enum {string} */
                ownedBy?: "audit_risk_committee";
                lastApproval?: {
                    approvedBy: string;
                    approverRole?: string;
                    /** Format: date-time */
                    approvedAt: string;
                    minuteReference?: string;
                    rationale?: string;
                };
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        GovernanceSettingUpdate: {
            validityRules?: {
                evidenceTypeKey: string;
                validityDays: number;
                /** @description Committee approver, not the security function */
                setBy?: string;
            }[];
            capOnOpenCriticalFinding?: number;
            capOnStaleAttestation?: number;
            domainWeightings?: {
                /** @enum {string} */
                domain?: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                /** Format: float */
                weighting?: number;
            }[];
            approval: {
                approvedBy: string;
                approverRole?: string;
                /** Format: date-time */
                approvedAt: string;
                minuteReference?: string;
                rationale?: string;
            };
        };
        AccessLogEntry: {
            /** Format: date-time */
            at: string;
            actor: string;
            /** @enum {string} */
            resourceType: "priority_asset" | "coverage_gap" | "exercise_finding" | "assurance_statement" | "export_package";
            resourceId?: string;
            compartment?: string;
            /** @enum {string} */
            outcome?: "allowed" | "denied";
        };
        ListEnvelopeAccessLogEntry: {
            data: {
                items: {
                    /** Format: date-time */
                    at: string;
                    actor: string;
                    /** @enum {string} */
                    resourceType: "priority_asset" | "coverage_gap" | "exercise_finding" | "assurance_statement" | "export_package";
                    resourceId?: string;
                    compartment?: string;
                    /** @enum {string} */
                    outcome?: "allowed" | "denied";
                }[];
                nextCursor?: string;
            };
            meta: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Authenticated but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque pagination cursor from a previous page. */
        Cursor: string;
        /** @description Page size (1–200). */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGovernanceSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Committee-owned validity rules, weightings, and caps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            validityRules?: {
                                evidenceTypeKey: string;
                                validityDays: number;
                                /** @description Committee approver, not the security function */
                                setBy?: string;
                            }[];
                            evidenceTypes?: {
                                /** @enum {string} */
                                key: "asset_attestation" | "emulation_exercise_report" | "response_plan_test" | "recovery_plan_test" | "detection_coverage_scan" | "escalation_path_test" | "third_party_assessment" | "contractual_clause_review" | "control_spend_statement" | "training_completion" | "incident_postmortem";
                                label: string;
                                defaultValidityDays?: number;
                            }[];
                            domains?: {
                                /** @enum {string} */
                                key: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                                name: string;
                                description?: string;
                                /** Format: float */
                                weighting?: number;
                            }[];
                            capOnOpenCriticalFinding?: number;
                            capOnStaleAttestation?: number;
                            /** @enum {string} */
                            ownedBy?: "audit_risk_committee";
                            lastApproval?: {
                                approvedBy: string;
                                approverRole?: string;
                                /** Format: date-time */
                                approvedAt: string;
                                minuteReference?: string;
                                rationale?: string;
                            };
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    updateGovernanceSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    validityRules?: {
                        evidenceTypeKey: string;
                        validityDays: number;
                        /** @description Committee approver, not the security function */
                        setBy?: string;
                    }[];
                    capOnOpenCriticalFinding?: number;
                    capOnStaleAttestation?: number;
                    domainWeightings?: {
                        /** @enum {string} */
                        domain?: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                        /** Format: float */
                        weighting?: number;
                    }[];
                    approval: {
                        approvedBy: string;
                        approverRole?: string;
                        /** Format: date-time */
                        approvedAt: string;
                        minuteReference?: string;
                        rationale?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Settings updated with an approval record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            validityRules?: {
                                evidenceTypeKey: string;
                                validityDays: number;
                                /** @description Committee approver, not the security function */
                                setBy?: string;
                            }[];
                            evidenceTypes?: {
                                /** @enum {string} */
                                key: "asset_attestation" | "emulation_exercise_report" | "response_plan_test" | "recovery_plan_test" | "detection_coverage_scan" | "escalation_path_test" | "third_party_assessment" | "contractual_clause_review" | "control_spend_statement" | "training_completion" | "incident_postmortem";
                                label: string;
                                defaultValidityDays?: number;
                            }[];
                            domains?: {
                                /** @enum {string} */
                                key: "risk_exposure" | "governance_and_leadership" | "strategic_context" | "resilience" | "response_capability" | "extended_ecosystem" | "efficient_investment";
                                name: string;
                                description?: string;
                                /** Format: float */
                                weighting?: number;
                            }[];
                            capOnOpenCriticalFinding?: number;
                            capOnStaleAttestation?: number;
                            /** @enum {string} */
                            ownedBy?: "audit_risk_committee";
                            lastApproval?: {
                                approvedBy: string;
                                approverRole?: string;
                                /** Format: date-time */
                                approvedAt: string;
                                minuteReference?: string;
                                rationale?: string;
                            };
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Authenticated but not permitted */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listAccessLog: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from a previous page. */
                cursor?: string;
                /** @description Page size (1–200). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access log page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /** Format: date-time */
                                at: string;
                                actor: string;
                                /** @enum {string} */
                                resourceType: "priority_asset" | "coverage_gap" | "exercise_finding" | "assurance_statement" | "export_package";
                                resourceId?: string;
                                compartment?: string;
                                /** @enum {string} */
                                outcome?: "allowed" | "denied";
                            }[];
                            nextCursor?: string;
                        };
                        meta: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
