/**
 * Score Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: domains
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/domains.openapi.types.js";
import { schemas } from "../schemas/domains.schemas.js";

/**
 * Entity: ScoreEntity
 * Description: Represents the Score domain model.
 * Source: schemas.DomainScore
 * Type: Persisted Entity (x-dynamodb)
 */
export const ScoreEntitySchema = schemas.DomainScore;
export type ScoreEntity = components["schemas"]["DomainScore"];
