/**
 * Repository interface for Asset
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AssetEntity
} from "../models/asset.entity.js";
import type {
  ListPriorityAssetsParams,
  PriorityAsset
} from "../types/index.js";
/**
 * AssetRepository Interface
 */
export interface AssetRepository extends CreateReadRepository<AssetEntity, PriorityAsset, string, ListPriorityAssetsParams> {

}
