/**
 * Repository interface for Attestation
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: assets
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AttestationEntity
} from "../models/attestation.entity.js";
import type {
  AssetAttestation
} from "../types/index.js";
/**
 * AttestationRepository Interface
 */
export interface AttestationRepository extends CreateReadRepository<AttestationEntity, AssetAttestation, string, Record<string, never>> {

}
