/**
 * Statement Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { StatementEntity } from "@vouchstone/core/assurance/models/index.js";
import { assuranceSchemas } from "@vouchstone/core/assurance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "asr";

export function createStatement(overrides: Partial<StatementEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    period: overrides.period ?? faker.lorem.word(),
    signedAt: overrides.signedAt ?? new Date().toISOString(),
    signedBy: overrides.signedBy ?? faker.lorem.word(),
    ...overrides,
  };

  return assuranceSchemas.AssuranceStatement.parse(raw);
}

export function statementBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createStatement(overrides));
}
