/**
 * DetectionInterval DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DetectionInterval DTOs
 *
 * DDD: Application DTOs for DetectionInterval use cases.
 */

import type { GetDetectionIntervalDistributionParams } from "@vouchstone/core/attribution/types";

export type GetDetectionIntervalDistributionInput = GetDetectionIntervalDistributionParams;

export type GetDetectionIntervalDistributionOutput = {};
