/**
 * DiscoveryShare DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DiscoveryShare DTOs
 *
 * DDD: Application DTOs for DiscoveryShare use cases.
 */

import type { GetDiscoveryShareReportParams } from "@vouchstone/core/attribution/types";

export type GetDiscoveryShareReportInput = GetDiscoveryShareReportParams;

export type GetDiscoveryShareReportOutput = {};
