/**
 * Handlers for Remediation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { FindingsDomainModule } from "../dependencies/findings-ddd.dependencies.js";
import type { UpdateRemediationCommitmentInput } from "@vouchstone/services/findings";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for PUT /v1/findings/{findingId}/remediation
 * Operation: updateRemediationCommitment
 */
export async function updateRemediationCommitment(
  request: FastifyRequest<{ Params: { findingId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: FindingsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateRemediationCommitmentInput = {
    findingId: request.params.findingId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.remediations.update.execute(input);
  return reply.code(200).send(result);
}


