/**
 * SettingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SettingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SettingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SettingRepository,
} from "@vouchstone/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SettingRepositoryDdb } from "./setting-repository.ddb.js";

/**
 * SettingRepositoryAdapter
 *
 * Implements SettingRepository port for infrastructure layer.
 */
export class SettingRepositoryAdapter implements SettingRepository {
  private readonly ddb: SettingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SettingRepositoryDdb(this.dynamoClient);
  }

  async getGovernanceSettings(input: Parameters<SettingRepository['getGovernanceSettings']>[0]): Promise<Awaited<ReturnType<SettingRepository['getGovernanceSettings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getGovernanceSettings(input);
  }

  async updateGovernanceSettings(input: Parameters<SettingRepository['updateGovernanceSettings']>[0]): Promise<Awaited<ReturnType<SettingRepository['updateGovernanceSettings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateGovernanceSettings(input);
  }
}
