/**
 * Evidence Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { EvidenceEntity } from "@vouchstone/core/evidence/models/index.js";
import { evidenceSchemas } from "@vouchstone/core/evidence";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "evd";

export function createEvidence(overrides: Partial<EvidenceEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    domains: overrides.domains ?? [],
    effectiveDate: overrides.effectiveDate ?? new Date().toISOString(),
    typeKey: overrides.typeKey ?? faker.lorem.word(),
    validity: overrides.validity ?? "valid",
    ...overrides,
  };

  return evidenceSchemas.EvidenceItem.parse(raw);
}

export function evidenceBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createEvidence(overrides));
}
