/**
 * Handlers for Attribution
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AttributionDomainModule } from "../dependencies/attribution-ddd.dependencies.js";
import type { AttributeIncidentDiscoveryInput } from "@vouchstone/services/attribution";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/incidents/{incidentId}/attribution
 * Operation: attributeIncidentDiscovery
 */
export async function attributeIncidentDiscovery(
  request: FastifyRequest<{ Params: { incidentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AttributionDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AttributeIncidentDiscoveryInput = {
    incidentId: request.params.incidentId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.attributions.get.execute(input);
  return reply.code(201).send(result);
}


