/**
 * GetExpiryForecast DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidence
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetEvidenceExpiryForecastParams } from "@vouchstone/core/evidence";

export function createGetExpiryForecastRequest(overrides: Partial<GetEvidenceExpiryForecastParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
