/**
 * Attribution Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: attribution
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AttributionEntity } from "@vouchstone/core/attribution/models/index.js";
import { attributionSchemas } from "@vouchstone/core/attribution";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "atr";

export function createAttribution(overrides: Partial<AttributionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    discoveredAt: overrides.discoveredAt ?? new Date().toISOString(),
    discovererClass: overrides.discovererClass ?? "security_function",
    incidentId: overrides.incidentId ?? faker.string.uuid(),
    ...overrides,
  };

  return attributionSchemas.DiscovererAttribution.parse(raw);
}

export function attributionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAttribution(overrides));
}
